# Generated by Django 6.1.1 on 2026-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(db_column='ID_Permiso', primary_key=True, serialize=False)),
                ('permiso', models.CharField(db_column='Permiso', max_length=20)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=250)),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_Rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='Rol', max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.AutoField(db_column='ID_RolPermiso', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roles_permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=100, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=250)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
