"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import subprocess
from pathlib import Path

from dotenv import load_dotenv


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# AMBIENTE
# ============================================================

def obtener_rama_git():
    """Obtiene la rama Git actual del proyecto."""
    try:
        resultado = subprocess.run(
            ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
            cwd=BASE_DIR,
            capture_output=True,
            text=True,
            check=True,
        )

        rama = resultado.stdout.strip()

        if rama == 'HEAD':
            raise RuntimeError(
                'El repositorio está en estado detached HEAD. '
                'No se puede determinar el ambiente de EduGes.'
            )

        return rama

    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        raise RuntimeError(
            'No se pudo determinar la rama Git actual. '
            'EduGes no puede iniciar de forma segura.'
        ) from exc


RAMA_GIT = obtener_rama_git()


AMBIENTES = {
    'desarrollo': {
        'archivo_env': '.env.desarrollo',
        'base_datos': 'EduGes',
        'debug': True,
    },
    'main': {
        'archivo_env': '.env.main',
        'base_datos': 'EduGes_Main',
        'debug': False,
    },
}


if RAMA_GIT not in AMBIENTES:
    raise RuntimeError(
        f'La rama Git "{RAMA_GIT}" no tiene un ambiente '
        'configurado para EduGes.'
    )


AMBIENTE = AMBIENTES[RAMA_GIT]


# ============================================================
# VARIABLES DE ENTORNO
# ============================================================

load_dotenv(
    BASE_DIR / AMBIENTE['archivo_env'],
    override=True,
)


# ============================================================
# VALIDACIÓN DE SEGURIDAD DEL AMBIENTE
# ============================================================

BASE_DE_DATOS_CONFIGURADA = os.getenv('DB_NAME')

if BASE_DE_DATOS_CONFIGURADA != AMBIENTE['base_datos']:
    raise RuntimeError(
        '\n'
        '============================================================\n'
        '❌ CONFIGURACIÓN INSEGURA DE EDUGES\n'
        '============================================================\n'
        f'Rama Git:             {RAMA_GIT}\n'
        f'Base configurada:     {BASE_DE_DATOS_CONFIGURADA}\n'
        f'Base esperada:        {AMBIENTE["base_datos"]}\n'
        '\n'
        'Django no iniciará para evitar trabajar con la base incorrecta.\n'
        '============================================================\n'
    )


DEBUG_CONFIGURADO = os.getenv(
    'DJANGO_DEBUG',
    'False',
).lower() in (
    '1',
    'true',
    'yes',
)

if DEBUG_CONFIGURADO != AMBIENTE['debug']:
    raise RuntimeError(
        '\n'
        '============================================================\n'
        '❌ CONFIGURACIÓN INSEGURA DE EDUGES\n'
        '============================================================\n'
        f'Rama Git:             {RAMA_GIT}\n'
        f'DJANGO_DEBUG:         {DEBUG_CONFIGURADO}\n'
        f'DEBUG esperado:       {AMBIENTE["debug"]}\n'
        '\n'
        'La configuración de DEBUG no coincide con el ambiente.\n'
        'Django no iniciará por seguridad.\n'
        '============================================================\n'
    )


# ============================================================
# INFORMACIÓN DEL AMBIENTE
# ============================================================

print('')
print('============================================================')
print(f'       EDUGES - AMBIENTE: {RAMA_GIT.upper()}')
print(f'       BASE DE DATOS:     {BASE_DE_DATOS_CONFIGURADA}')
print('============================================================')
print('')


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

DEBUG = DEBUG_CONFIGURADO

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    'core',
    
    'django.contrib.staticfiles',
    'django.contrib.sessions',

    'rest_framework',
    'usuarios',
    'pacientes',
    'profesionales',
    'turnos',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URLS / WSGI
# ============================================================

ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.parent / 'Frontend' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None,

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'APIs.autenticacion.autenticacion.UsuarioSessionAuthentication',
    ),
}


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR.parent / 'Frontend' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# ============================================================
# EMAIL
# ============================================================

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ============================================================
# SESSION
# ============================================================

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


# ============================================================
# CACHE
# ============================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'eduges-rate-limit',
    },
}