# Generated by Django 6.1.1 on 2026-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionProfesional',
            fields=[
                ('id_asignacion_profesional', models.AutoField(db_column='ID_AsignacionProfesional', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='FechaInicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='FechaFin', null=True)),
            ],
            options={
                'db_table': 'asignaciones_profesionales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(db_column='ID_Especialidad', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(db_column='Especialidad', max_length=100)),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.AutoField(db_column='ID_Profesionales', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('dni', models.CharField(db_column='DNI', max_length=20)),
                ('matricula', models.CharField(db_column='Matricula', max_length=50)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=50, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=50, null=True)),
            ],
            options={
                'db_table': 'profesionales',
                'managed': False,
            },
        ),
    ]
