--
-- PostgreSQL database dump
--

\restrict Y5ydaXqwAqilDudQIM3WUEzwofTMY8L1CyRcwXve6xIXbDsLDCrrtmQphuVgRig

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-23 16:35:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 244 (class 1259 OID 16960)
-- Name: asignaciones_profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asignaciones_profesionales (
    "ID_AsignacionProfesional" integer CONSTRAINT asignaciones_profesionales_id_asignacionprofesional_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT asignaciones_profesionales_id_paciente_not_null NOT NULL,
    "ID_Profesional" integer CONSTRAINT asignaciones_profesionales_id_profesional_not_null NOT NULL,
    "FechaInicio" date CONSTRAINT asignaciones_profesionales_fechainicio_not_null NOT NULL,
    "FechaFin" date,
    CONSTRAINT ck_asignacionesprofesionales_fechas CHECK ((("FechaFin" IS NULL) OR ("FechaFin" >= "FechaInicio")))
);


--
-- TOC entry 243 (class 1259 OID 16959)
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.asignaciones_profesionales_id_asignacionprofesional_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5226 (class 0 OID 0)
-- Dependencies: 243
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.asignaciones_profesionales_id_asignacionprofesional_seq OWNED BY public.asignaciones_profesionales."ID_AsignacionProfesional";


--
-- TOC entry 251 (class 1259 OID 17119)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- TOC entry 250 (class 1259 OID 17118)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16813)
-- Name: especialidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.especialidades (
    "ID_Especialidad" integer CONSTRAINT especialidades_id_especialidad_not_null NOT NULL,
    "Especialidad" character varying(100) CONSTRAINT especialidades_especialidad_not_null NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 16812)
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.especialidades_id_especialidad_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5227 (class 0 OID 0)
-- Dependencies: 227
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.especialidades_id_especialidad_seq OWNED BY public.especialidades."ID_Especialidad";


--
-- TOC entry 247 (class 1259 OID 17074)
-- Name: estados_obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_obras_sociales (
    "ID_EstadoObraSocial" integer NOT NULL,
    "Descripcion" character varying(100) NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 16791)
-- Name: estados_pacientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_pacientes (
    "ID_EstadoPaciente" integer CONSTRAINT estados_pacientes_id_estadopaciente_not_null NOT NULL,
    "Estado" character varying(50) CONSTRAINT estados_pacientes_estado_not_null NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16790)
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.estados_pacientes_id_estadopaciente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5228 (class 0 OID 0)
-- Dependencies: 223
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.estados_pacientes_id_estadopaciente_seq OWNED BY public.estados_pacientes."ID_EstadoPaciente";


--
-- TOC entry 253 (class 1259 OID 17399)
-- Name: estados_profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_profesionales (
    "ID_EstadoProfesional" integer,
    "Estado" character varying(100)
);


--
-- TOC entry 226 (class 1259 OID 16802)
-- Name: estados_turnos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_turnos (
    "ID_EstadoTurno" integer CONSTRAINT estados_turnos_id_estadoturno_not_null NOT NULL,
    "Estado" character varying(50) CONSTRAINT estados_turnos_estado_not_null NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16801)
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.estados_turnos_id_estadoturno_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5229 (class 0 OID 0)
-- Dependencies: 225
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.estados_turnos_id_estadoturno_seq OWNED BY public.estados_turnos."ID_EstadoTurno";


--
-- TOC entry 232 (class 1259 OID 16835)
-- Name: obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.obras_sociales (
    "ID_ObraSocial" integer CONSTRAINT obras_sociales_id_obrasocial_not_null NOT NULL,
    "Nombre" character varying(150) CONSTRAINT obras_sociales_nombre_not_null NOT NULL,
    "Contacto" character varying(150),
    "Mail" character varying(150),
    "Web" character varying(255),
    "ID_TipoOS" integer CONSTRAINT obras_sociales_id_tipoos_not_null NOT NULL,
    "ID_EstadoObraSocial" integer NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 16834)
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.obras_sociales_id_obrasocial_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5230 (class 0 OID 0)
-- Dependencies: 231
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.obras_sociales_id_obrasocial_seq OWNED BY public.obras_sociales."ID_ObraSocial";


--
-- TOC entry 238 (class 1259 OID 16890)
-- Name: pacientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pacientes (
    "ID_Paciente" integer CONSTRAINT pacientes_id_paciente_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT pacientes_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT pacientes_apellido_not_null NOT NULL,
    "DNI" character varying(20) CONSTRAINT pacientes_dni_not_null NOT NULL,
    "FechaNacimiento" date CONSTRAINT pacientes_fechanacimiento_not_null NOT NULL,
    "Direccion" character varying(255) NOT NULL,
    "CUD_Vencimiento" date CONSTRAINT pacientes_cud_vencimiento_not_null NOT NULL,
    "ID_ObraSocial" integer CONSTRAINT pacientes_id_obrasocial_not_null NOT NULL,
    "ID_EstadoPaciente" integer CONSTRAINT pacientes_id_estadopaciente_not_null NOT NULL,
    "Consentimiento" boolean NOT NULL,
    "NumeroAfiliado" character varying(20) NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 16889)
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pacientes_id_paciente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5231 (class 0 OID 0)
-- Dependencies: 237
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pacientes_id_paciente_seq OWNED BY public.pacientes."ID_Paciente";


--
-- TOC entry 240 (class 1259 OID 16919)
-- Name: pacientes_tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pacientes_tutores (
    "ID_PacienteTutor" integer CONSTRAINT pacientes_tutores_id_pacientetutor_not_null NOT NULL,
    "ID_Tutor" integer CONSTRAINT pacientes_tutores_id_tutor_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT pacientes_tutores_id_paciente_not_null NOT NULL,
    "ID_Parentesco" integer CONSTRAINT pacientes_tutores_id_parentesco_not_null NOT NULL,
    "ResponsablePrincipal" boolean DEFAULT false CONSTRAINT pacientes_tutores_responsableprincipal_not_null NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 16918)
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pacientes_tutores_id_pacientetutor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5232 (class 0 OID 0)
-- Dependencies: 239
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pacientes_tutores_id_pacientetutor_seq OWNED BY public.pacientes_tutores."ID_PacienteTutor";


--
-- TOC entry 220 (class 1259 OID 16769)
-- Name: parentescos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parentescos (
    "ID_Parentesco" integer CONSTRAINT parentescos_id_parentesco_not_null NOT NULL,
    "Descripcion" character varying(100) CONSTRAINT parentescos_descripcion_not_null NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16768)
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.parentescos_id_parentesco_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5233 (class 0 OID 0)
-- Dependencies: 219
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.parentescos_id_parentesco_seq OWNED BY public.parentescos."ID_Parentesco";


--
-- TOC entry 248 (class 1259 OID 17089)
-- Name: permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos (
    "ID_Permiso" integer NOT NULL,
    "Permiso" character varying(20) NOT NULL,
    "Descripcion" character varying(250) NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 16862)
-- Name: profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profesionales (
    "ID_Profesionales" integer CONSTRAINT profesionales_id_profesional_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT profesionales_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT profesionales_apellido_not_null NOT NULL,
    "DNI" character varying(20) CONSTRAINT profesionales_dni_not_null NOT NULL,
    "Matricula" character varying(50) CONSTRAINT profesionales_matricula_not_null NOT NULL,
    "ID_Especialidad" integer CONSTRAINT profesionales_id_especialidad_not_null NOT NULL,
    "Contacto" character varying(50),
    "Mail" character varying(50),
    "ID_Usuario" integer NOT NULL,
    "ID_EstadoProfesional" integer NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 16861)
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.profesionales_id_profesional_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5234 (class 0 OID 0)
-- Dependencies: 235
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.profesionales_id_profesional_seq OWNED BY public.profesionales."ID_Profesionales";


--
-- TOC entry 242 (class 1259 OID 16950)
-- Name: registros_de_sesiones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_de_sesiones (
    "ID_RegistroSesion" integer CONSTRAINT registros_de_sesiones_id_registrosesion_not_null NOT NULL,
    "NotaClinica" character varying(5000) NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 16949)
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.registros_de_sesiones_id_registrosesion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5235 (class 0 OID 0)
-- Dependencies: 241
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.registros_de_sesiones_id_registrosesion_seq OWNED BY public.registros_de_sesiones."ID_RegistroSesion";


--
-- TOC entry 230 (class 1259 OID 16824)
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    "ID_Rol" integer CONSTRAINT roles_id_rol_not_null NOT NULL,
    "Rol" character varying(50) CONSTRAINT roles_rol_not_null NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 16823)
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.roles_id_rol_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5236 (class 0 OID 0)
-- Dependencies: 229
-- Name: roles_id_rol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.roles_id_rol_seq OWNED BY public.roles."ID_Rol";


--
-- TOC entry 252 (class 1259 OID 17346)
-- Name: roles_permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_permisos (
    "ID_RolPermiso" integer NOT NULL,
    "ID_Rol" integer NOT NULL,
    "ID_Permiso" integer NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 16780)
-- Name: tipos_obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_obras_sociales (
    "ID_TipoOS" integer CONSTRAINT tipos_obras_sociales_id_tipoos_not_null NOT NULL,
    "Tipo" character varying(100) CONSTRAINT tipos_obras_sociales_tipo_not_null NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 16779)
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tipos_obras_sociales_id_tipoos_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5237 (class 0 OID 0)
-- Dependencies: 221
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tipos_obras_sociales_id_tipoos_seq OWNED BY public.tipos_obras_sociales."ID_TipoOS";


--
-- TOC entry 246 (class 1259 OID 17041)
-- Name: turnos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.turnos (
    "ID_Turnos" integer CONSTRAINT turnos_id_turno_not_null NOT NULL,
    "Fecha" date CONSTRAINT turnos_fecha_not_null NOT NULL,
    "Hora" time without time zone CONSTRAINT turnos_hora_not_null NOT NULL,
    "ID_EstadoTurno" integer CONSTRAINT turnos_id_estadoturno_not_null NOT NULL,
    "ID_RegistroSesion" integer,
    "ID_Profesional" integer CONSTRAINT turnos_id_profesional_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT turnos_id_paciente_not_null NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 17040)
-- Name: turnos_id_turno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.turnos_id_turno_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5238 (class 0 OID 0)
-- Dependencies: 245
-- Name: turnos_id_turno_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.turnos_id_turno_seq OWNED BY public.turnos."ID_Turnos";


--
-- TOC entry 234 (class 1259 OID 16852)
-- Name: tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutores (
    "ID_Tutor" integer CONSTRAINT tutores_id_tutor_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT tutores_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT tutores_apellido_not_null NOT NULL,
    "TelefonoFijo" character varying(30),
    "TelefonoMovil" character varying(30),
    "Mail" character varying(150)
);


--
-- TOC entry 233 (class 1259 OID 16851)
-- Name: tutores_id_tutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tutores_id_tutor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5239 (class 0 OID 0)
-- Dependencies: 233
-- Name: tutores_id_tutor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tutores_id_tutor_seq OWNED BY public.tutores."ID_Tutor";


--
-- TOC entry 249 (class 1259 OID 17099)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    "ID_Usuario" integer NOT NULL,
    "Usuario" character varying NOT NULL,
    "ID_Rol" integer,
    "Password" character varying NOT NULL
);


--
-- TOC entry 4959 (class 2604 OID 16963)
-- Name: asignaciones_profesionales ID_AsignacionProfesional; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales ALTER COLUMN "ID_AsignacionProfesional" SET DEFAULT nextval('public.asignaciones_profesionales_id_asignacionprofesional_seq'::regclass);


--
-- TOC entry 4950 (class 2604 OID 16816)
-- Name: especialidades ID_Especialidad; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades ALTER COLUMN "ID_Especialidad" SET DEFAULT nextval('public.especialidades_id_especialidad_seq'::regclass);


--
-- TOC entry 4948 (class 2604 OID 16794)
-- Name: estados_pacientes ID_EstadoPaciente; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes ALTER COLUMN "ID_EstadoPaciente" SET DEFAULT nextval('public.estados_pacientes_id_estadopaciente_seq'::regclass);


--
-- TOC entry 4949 (class 2604 OID 16805)
-- Name: estados_turnos ID_EstadoTurno; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos ALTER COLUMN "ID_EstadoTurno" SET DEFAULT nextval('public.estados_turnos_id_estadoturno_seq'::regclass);


--
-- TOC entry 4952 (class 2604 OID 16838)
-- Name: obras_sociales ID_ObraSocial; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales ALTER COLUMN "ID_ObraSocial" SET DEFAULT nextval('public.obras_sociales_id_obrasocial_seq'::regclass);


--
-- TOC entry 4955 (class 2604 OID 16893)
-- Name: pacientes ID_Paciente; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes ALTER COLUMN "ID_Paciente" SET DEFAULT nextval('public.pacientes_id_paciente_seq'::regclass);


--
-- TOC entry 4956 (class 2604 OID 16922)
-- Name: pacientes_tutores ID_PacienteTutor; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores ALTER COLUMN "ID_PacienteTutor" SET DEFAULT nextval('public.pacientes_tutores_id_pacientetutor_seq'::regclass);


--
-- TOC entry 4946 (class 2604 OID 16772)
-- Name: parentescos ID_Parentesco; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos ALTER COLUMN "ID_Parentesco" SET DEFAULT nextval('public.parentescos_id_parentesco_seq'::regclass);


--
-- TOC entry 4954 (class 2604 OID 16865)
-- Name: profesionales ID_Profesionales; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales ALTER COLUMN "ID_Profesionales" SET DEFAULT nextval('public.profesionales_id_profesional_seq'::regclass);


--
-- TOC entry 4958 (class 2604 OID 16953)
-- Name: registros_de_sesiones ID_RegistroSesion; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_de_sesiones ALTER COLUMN "ID_RegistroSesion" SET DEFAULT nextval('public.registros_de_sesiones_id_registrosesion_seq'::regclass);


--
-- TOC entry 4951 (class 2604 OID 16827)
-- Name: roles ID_Rol; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles ALTER COLUMN "ID_Rol" SET DEFAULT nextval('public.roles_id_rol_seq'::regclass);


--
-- TOC entry 4947 (class 2604 OID 16783)
-- Name: tipos_obras_sociales ID_TipoOS; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales ALTER COLUMN "ID_TipoOS" SET DEFAULT nextval('public.tipos_obras_sociales_id_tipoos_seq'::regclass);


--
-- TOC entry 4960 (class 2604 OID 17044)
-- Name: turnos ID_Turnos; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos ALTER COLUMN "ID_Turnos" SET DEFAULT nextval('public.turnos_id_turno_seq'::regclass);


--
-- TOC entry 4953 (class 2604 OID 16855)
-- Name: tutores ID_Tutor; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores ALTER COLUMN "ID_Tutor" SET DEFAULT nextval('public.tutores_id_tutor_seq'::regclass);


--
-- TOC entry 5211 (class 0 OID 16960)
-- Dependencies: 244
-- Data for Name: asignaciones_profesionales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.asignaciones_profesionales ("ID_AsignacionProfesional", "ID_Paciente", "ID_Profesional", "FechaInicio", "FechaFin") FROM stdin;
\.


--
-- TOC entry 5218 (class 0 OID 17119)
-- Dependencies: 251
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-04 16:17:01.593189-03
2	auth	0001_initial	2026-09-04 16:17:01.63556-03
3	admin	0001_initial	2026-09-04 16:17:01.680545-03
4	admin	0002_logentry_remove_auto_add	2026-09-04 16:17:01.685563-03
5	admin	0003_logentry_add_action_flag_choices	2026-09-04 16:17:01.692201-03
6	contenttypes	0002_remove_content_type_name	2026-09-04 16:17:01.703275-03
7	auth	0002_alter_permission_name_max_length	2026-09-04 16:17:01.710391-03
8	auth	0003_alter_user_email_max_length	2026-09-04 16:17:01.715726-03
9	auth	0004_alter_user_username_opts	2026-09-04 16:17:01.72105-03
10	auth	0005_alter_user_last_login_null	2026-09-04 16:17:01.729231-03
11	auth	0006_require_contenttypes_0002	2026-09-04 16:17:01.730177-03
12	auth	0007_alter_validators_add_error_messages	2026-09-04 16:17:01.735125-03
13	auth	0008_alter_user_username_max_length	2026-09-04 16:17:01.745395-03
14	auth	0009_alter_user_last_name_max_length	2026-09-04 16:17:01.754309-03
15	auth	0010_alter_group_name_max_length	2026-09-04 16:17:01.763783-03
16	auth	0011_update_proxy_permissions	2026-09-04 16:17:01.775928-03
17	auth	0012_alter_user_first_name_max_length	2026-09-04 16:17:01.787677-03
18	sessions	0001_initial	2026-09-04 16:17:01.808238-03
19	pacientes	0001_initial	2026-09-07 17:13:45.120824-03
20	profesionales	0001_initial	2026-09-07 17:13:45.124764-03
21	turnos	0001_initial	2026-09-07 17:13:45.126818-03
22	usuarios	0001_initial	2026-09-07 17:13:45.129718-03
\.


--
-- TOC entry 5195 (class 0 OID 16813)
-- Dependencies: 228
-- Data for Name: especialidades; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.especialidades ("ID_Especialidad", "Especialidad") FROM stdin;
\.


--
-- TOC entry 5214 (class 0 OID 17074)
-- Dependencies: 247
-- Data for Name: estados_obras_sociales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_obras_sociales ("ID_EstadoObraSocial", "Descripcion") FROM stdin;
\.


--
-- TOC entry 5191 (class 0 OID 16791)
-- Dependencies: 224
-- Data for Name: estados_pacientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_pacientes ("ID_EstadoPaciente", "Estado") FROM stdin;
1	Activo
2	Inactivo
\.


--
-- TOC entry 5220 (class 0 OID 17399)
-- Dependencies: 253
-- Data for Name: estados_profesionales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_profesionales ("ID_EstadoProfesional", "Estado") FROM stdin;
\.


--
-- TOC entry 5193 (class 0 OID 16802)
-- Dependencies: 226
-- Data for Name: estados_turnos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_turnos ("ID_EstadoTurno", "Estado") FROM stdin;
1	Pendiente
2	Confirmado
3	Cancelado
4	Realizado
\.


--
-- TOC entry 5199 (class 0 OID 16835)
-- Dependencies: 232
-- Data for Name: obras_sociales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.obras_sociales ("ID_ObraSocial", "Nombre", "Contacto", "Mail", "Web", "ID_TipoOS", "ID_EstadoObraSocial") FROM stdin;
\.


--
-- TOC entry 5205 (class 0 OID 16890)
-- Dependencies: 238
-- Data for Name: pacientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pacientes ("ID_Paciente", "Nombre", "Apellido", "DNI", "FechaNacimiento", "Direccion", "CUD_Vencimiento", "ID_ObraSocial", "ID_EstadoPaciente", "Consentimiento", "NumeroAfiliado") FROM stdin;
\.


--
-- TOC entry 5207 (class 0 OID 16919)
-- Dependencies: 240
-- Data for Name: pacientes_tutores; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pacientes_tutores ("ID_PacienteTutor", "ID_Tutor", "ID_Paciente", "ID_Parentesco", "ResponsablePrincipal") FROM stdin;
\.


--
-- TOC entry 5187 (class 0 OID 16769)
-- Dependencies: 220
-- Data for Name: parentescos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.parentescos ("ID_Parentesco", "Descripcion") FROM stdin;
\.


--
-- TOC entry 5215 (class 0 OID 17089)
-- Dependencies: 248
-- Data for Name: permisos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.permisos ("ID_Permiso", "Permiso", "Descripcion") FROM stdin;
\.


--
-- TOC entry 5203 (class 0 OID 16862)
-- Dependencies: 236
-- Data for Name: profesionales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profesionales ("ID_Profesionales", "Nombre", "Apellido", "DNI", "Matricula", "ID_Especialidad", "Contacto", "Mail", "ID_Usuario", "ID_EstadoProfesional") FROM stdin;
\.


--
-- TOC entry 5209 (class 0 OID 16950)
-- Dependencies: 242
-- Data for Name: registros_de_sesiones; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.registros_de_sesiones ("ID_RegistroSesion", "NotaClinica") FROM stdin;
\.


--
-- TOC entry 5197 (class 0 OID 16824)
-- Dependencies: 230
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles ("ID_Rol", "Rol") FROM stdin;
1	Administrador
2	Profesional
\.


--
-- TOC entry 5219 (class 0 OID 17346)
-- Dependencies: 252
-- Data for Name: roles_permisos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles_permisos ("ID_RolPermiso", "ID_Rol", "ID_Permiso") FROM stdin;
\.


--
-- TOC entry 5189 (class 0 OID 16780)
-- Dependencies: 222
-- Data for Name: tipos_obras_sociales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tipos_obras_sociales ("ID_TipoOS", "Tipo") FROM stdin;
\.


--
-- TOC entry 5213 (class 0 OID 17041)
-- Dependencies: 246
-- Data for Name: turnos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.turnos ("ID_Turnos", "Fecha", "Hora", "ID_EstadoTurno", "ID_RegistroSesion", "ID_Profesional", "ID_Paciente") FROM stdin;
\.


--
-- TOC entry 5201 (class 0 OID 16852)
-- Dependencies: 234
-- Data for Name: tutores; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tutores ("ID_Tutor", "Nombre", "Apellido", "TelefonoFijo", "TelefonoMovil", "Mail") FROM stdin;
\.


--
-- TOC entry 5216 (class 0 OID 17099)
-- Dependencies: 249
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios ("ID_Usuario", "Usuario", "ID_Rol", "Password") FROM stdin;
\.


--
-- TOC entry 5240 (class 0 OID 0)
-- Dependencies: 243
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.asignaciones_profesionales_id_asignacionprofesional_seq', 1, false);


--
-- TOC entry 5241 (class 0 OID 0)
-- Dependencies: 250
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- TOC entry 5242 (class 0 OID 0)
-- Dependencies: 227
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.especialidades_id_especialidad_seq', 1, false);


--
-- TOC entry 5243 (class 0 OID 0)
-- Dependencies: 223
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estados_pacientes_id_estadopaciente_seq', 2, true);


--
-- TOC entry 5244 (class 0 OID 0)
-- Dependencies: 225
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estados_turnos_id_estadoturno_seq', 4, true);


--
-- TOC entry 5245 (class 0 OID 0)
-- Dependencies: 231
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.obras_sociales_id_obrasocial_seq', 1, false);


--
-- TOC entry 5246 (class 0 OID 0)
-- Dependencies: 237
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pacientes_id_paciente_seq', 1, false);


--
-- TOC entry 5247 (class 0 OID 0)
-- Dependencies: 239
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pacientes_tutores_id_pacientetutor_seq', 1, false);


--
-- TOC entry 5248 (class 0 OID 0)
-- Dependencies: 219
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.parentescos_id_parentesco_seq', 1, false);


--
-- TOC entry 5249 (class 0 OID 0)
-- Dependencies: 235
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.profesionales_id_profesional_seq', 1, false);


--
-- TOC entry 5250 (class 0 OID 0)
-- Dependencies: 241
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.registros_de_sesiones_id_registrosesion_seq', 1, false);


--
-- TOC entry 5251 (class 0 OID 0)
-- Dependencies: 229
-- Name: roles_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_id_rol_seq', 2, true);


--
-- TOC entry 5252 (class 0 OID 0)
-- Dependencies: 221
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tipos_obras_sociales_id_tipoos_seq', 1, false);


--
-- TOC entry 5253 (class 0 OID 0)
-- Dependencies: 245
-- Name: turnos_id_turno_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.turnos_id_turno_seq', 1, false);


--
-- TOC entry 5254 (class 0 OID 0)
-- Dependencies: 233
-- Name: tutores_id_tutor_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tutores_id_tutor_seq', 1, false);


--
-- TOC entry 4991 (class 2606 OID 17367)
-- Name: profesionales UQ_Profesionales_ID_Usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT "UQ_Profesionales_ID_Usuario" UNIQUE ("ID_Usuario");


--
-- TOC entry 5023 (class 2606 OID 17361)
-- Name: roles_permisos UQ_RolesPermisos_Rol_Permiso; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT "UQ_RolesPermisos_Rol_Permiso" UNIQUE ("ID_Rol", "ID_Permiso");


--
-- TOC entry 5011 (class 2606 OID 16970)
-- Name: asignaciones_profesionales asignaciones_profesionales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT asignaciones_profesionales_pkey PRIMARY KEY ("ID_AsignacionProfesional");


--
-- TOC entry 5021 (class 2606 OID 17129)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4979 (class 2606 OID 16822)
-- Name: especialidades especialidades_especialidad_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades
    ADD CONSTRAINT especialidades_especialidad_key UNIQUE ("Especialidad");


--
-- TOC entry 4981 (class 2606 OID 16820)
-- Name: especialidades especialidades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades
    ADD CONSTRAINT especialidades_pkey PRIMARY KEY ("ID_Especialidad");


--
-- TOC entry 4971 (class 2606 OID 16800)
-- Name: estados_pacientes estados_pacientes_estado_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes
    ADD CONSTRAINT estados_pacientes_estado_key UNIQUE ("Estado");


--
-- TOC entry 4973 (class 2606 OID 16798)
-- Name: estados_pacientes estados_pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes
    ADD CONSTRAINT estados_pacientes_pkey PRIMARY KEY ("ID_EstadoPaciente");


--
-- TOC entry 4975 (class 2606 OID 16811)
-- Name: estados_turnos estados_turnos_estado_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos
    ADD CONSTRAINT estados_turnos_estado_key UNIQUE ("Estado");


--
-- TOC entry 4977 (class 2606 OID 16809)
-- Name: estados_turnos estados_turnos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos
    ADD CONSTRAINT estados_turnos_pkey PRIMARY KEY ("ID_EstadoTurno");


--
-- TOC entry 4987 (class 2606 OID 16845)
-- Name: obras_sociales obras_sociales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales
    ADD CONSTRAINT obras_sociales_pkey PRIMARY KEY ("ID_ObraSocial");


--
-- TOC entry 4999 (class 2606 OID 16907)
-- Name: pacientes pacientes_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_dni_key UNIQUE ("DNI");


--
-- TOC entry 5001 (class 2606 OID 16905)
-- Name: pacientes pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_pkey PRIMARY KEY ("ID_Paciente");


--
-- TOC entry 5003 (class 2606 OID 16930)
-- Name: pacientes_tutores pacientes_tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT pacientes_tutores_pkey PRIMARY KEY ("ID_PacienteTutor");


--
-- TOC entry 4963 (class 2606 OID 16778)
-- Name: parentescos parentescos_descripcion_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos
    ADD CONSTRAINT parentescos_descripcion_key UNIQUE ("Descripcion");


--
-- TOC entry 4965 (class 2606 OID 16776)
-- Name: parentescos parentescos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos
    ADD CONSTRAINT parentescos_pkey PRIMARY KEY ("ID_Parentesco");


--
-- TOC entry 4993 (class 2606 OID 16876)
-- Name: profesionales profesionales_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_dni_key UNIQUE ("DNI");


--
-- TOC entry 4995 (class 2606 OID 16878)
-- Name: profesionales profesionales_matricula_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_matricula_key UNIQUE ("Matricula");


--
-- TOC entry 4997 (class 2606 OID 16874)
-- Name: profesionales profesionales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_pkey PRIMARY KEY ("ID_Profesionales");


--
-- TOC entry 5009 (class 2606 OID 16958)
-- Name: registros_de_sesiones registros_de_sesiones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_de_sesiones
    ADD CONSTRAINT registros_de_sesiones_pkey PRIMARY KEY ("ID_RegistroSesion");


--
-- TOC entry 4983 (class 2606 OID 16831)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY ("ID_Rol");


--
-- TOC entry 4985 (class 2606 OID 16833)
-- Name: roles roles_rol_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_rol_key UNIQUE ("Rol");


--
-- TOC entry 4967 (class 2606 OID 16787)
-- Name: tipos_obras_sociales tipos_obras_sociales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales
    ADD CONSTRAINT tipos_obras_sociales_pkey PRIMARY KEY ("ID_TipoOS");


--
-- TOC entry 4969 (class 2606 OID 16789)
-- Name: tipos_obras_sociales tipos_obras_sociales_tipo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales
    ADD CONSTRAINT tipos_obras_sociales_tipo_key UNIQUE ("Tipo");


--
-- TOC entry 5013 (class 2606 OID 17052)
-- Name: turnos turnos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT turnos_pkey PRIMARY KEY ("ID_Turnos");


--
-- TOC entry 4989 (class 2606 OID 16860)
-- Name: tutores tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores
    ADD CONSTRAINT tutores_pkey PRIMARY KEY ("ID_Tutor");


--
-- TOC entry 5007 (class 2606 OID 16932)
-- Name: pacientes_tutores uq_paciente_tutor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT uq_paciente_tutor UNIQUE ("ID_Paciente", "ID_Tutor");


--
-- TOC entry 5017 (class 2606 OID 17378)
-- Name: usuarios uq_usuarios_usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uq_usuarios_usuario UNIQUE ("Usuario");


--
-- TOC entry 5019 (class 2606 OID 17388)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY ("ID_Usuario");


--
-- TOC entry 5004 (class 1259 OID 17379)
-- Name: uq_paciente_responsable_principal; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_paciente_responsable_principal ON public.pacientes_tutores USING btree ("ID_Paciente") WHERE ("ResponsablePrincipal" = true);


--
-- TOC entry 5005 (class 1259 OID 16948)
-- Name: uq_paciente_responsableprincipal; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_paciente_responsableprincipal ON public.pacientes_tutores USING btree ("ID_Paciente") WHERE ("ResponsablePrincipal" = true);


--
-- TOC entry 5014 (class 1259 OID 17380)
-- Name: uq_turno_profesional_fecha_hora; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_turno_profesional_fecha_hora ON public.turnos USING btree ("ID_Profesional", "Fecha", "Hora");


--
-- TOC entry 5015 (class 1259 OID 17381)
-- Name: uq_turno_registro_sesion; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_turno_registro_sesion ON public.turnos USING btree ("ID_RegistroSesion") WHERE ("ID_RegistroSesion" IS NOT NULL);


--
-- TOC entry 5032 (class 2606 OID 16971)
-- Name: asignaciones_profesionales fk_asignacionesprofesionales_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT fk_asignacionesprofesionales_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente");


--
-- TOC entry 5033 (class 2606 OID 16976)
-- Name: asignaciones_profesionales fk_asignacionesprofesionales_profesional; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT fk_asignacionesprofesionales_profesional FOREIGN KEY ("ID_Profesional") REFERENCES public.profesionales("ID_Profesionales");


--
-- TOC entry 5024 (class 2606 OID 16846)
-- Name: obras_sociales fk_obrassociales_tipos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales
    ADD CONSTRAINT fk_obrassociales_tipos FOREIGN KEY ("ID_TipoOS") REFERENCES public.tipos_obras_sociales("ID_TipoOS");


--
-- TOC entry 5027 (class 2606 OID 16913)
-- Name: pacientes fk_pacientes_estados; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT fk_pacientes_estados FOREIGN KEY ("ID_EstadoPaciente") REFERENCES public.estados_pacientes("ID_EstadoPaciente");


--
-- TOC entry 5028 (class 2606 OID 16908)
-- Name: pacientes fk_pacientes_obrassociales; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT fk_pacientes_obrassociales FOREIGN KEY ("ID_ObraSocial") REFERENCES public.obras_sociales("ID_ObraSocial");


--
-- TOC entry 5029 (class 2606 OID 16938)
-- Name: pacientes_tutores fk_pacientestutores_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente") ON DELETE CASCADE;


--
-- TOC entry 5030 (class 2606 OID 16943)
-- Name: pacientes_tutores fk_pacientestutores_parentesco; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_parentesco FOREIGN KEY ("ID_Parentesco") REFERENCES public.parentescos("ID_Parentesco");


--
-- TOC entry 5031 (class 2606 OID 16933)
-- Name: pacientes_tutores fk_pacientestutores_tutor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_tutor FOREIGN KEY ("ID_Tutor") REFERENCES public.tutores("ID_Tutor") ON DELETE CASCADE;


--
-- TOC entry 5025 (class 2606 OID 16879)
-- Name: profesionales fk_profesionales_especialidades; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_especialidades FOREIGN KEY ("ID_Especialidad") REFERENCES public.especialidades("ID_Especialidad");


--
-- TOC entry 5026 (class 2606 OID 17394)
-- Name: profesionales fk_profesionales_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_usuario FOREIGN KEY ("ID_Usuario") REFERENCES public.usuarios("ID_Usuario");


--
-- TOC entry 5034 (class 2606 OID 17053)
-- Name: turnos fk_turnos_estados; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_estados FOREIGN KEY ("ID_EstadoTurno") REFERENCES public.estados_turnos("ID_EstadoTurno");


--
-- TOC entry 5035 (class 2606 OID 17068)
-- Name: turnos fk_turnos_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente");


--
-- TOC entry 5036 (class 2606 OID 17063)
-- Name: turnos fk_turnos_profesional; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_profesional FOREIGN KEY ("ID_Profesional") REFERENCES public.profesionales("ID_Profesionales");


--
-- TOC entry 5037 (class 2606 OID 17058)
-- Name: turnos fk_turnos_registrosesion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_registrosesion FOREIGN KEY ("ID_RegistroSesion") REFERENCES public.registros_de_sesiones("ID_RegistroSesion") ON DELETE SET NULL;


--
-- TOC entry 5038 (class 2606 OID 17389)
-- Name: usuarios fk_usuarios_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_rol FOREIGN KEY ("ID_Rol") REFERENCES public.roles("ID_Rol");


-- Completed on 2026-09-23 16:35:24

--
-- PostgreSQL database dump complete
--

\unrestrict Y5ydaXqwAqilDudQIM3WUEzwofTMY8L1CyRcwXve6xIXbDsLDCrrtmQphuVgRig

