--
-- PostgreSQL database dump
--

\restrict Oh7mZY3Dle1DrhdRKooctAjdBGc2uxhOcmKxxl8w8blFYDngeenFdeVObILjOOJ

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-07 17:16:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 244 (class 1259 OID 16960)
-- Name: asignaciones_profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asignaciones_profesionales (
    "ID_AsignacionProfesional" integer CONSTRAINT asignaciones_profesionales_id_asignacionprofesional_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT asignaciones_profesionales_id_paciente_not_null NOT NULL,
    "ID_Profesional" integer CONSTRAINT asignaciones_profesionales_id_profesional_not_null NOT NULL,
    "FechaInicio" date CONSTRAINT asignaciones_profesionales_fechainicio_not_null NOT NULL,
    "FechaFin" date,
    CONSTRAINT ck_asignacionesprofesionales_fechas CHECK ((("FechaFin" IS NULL) OR ("FechaFin" >= "FechaInicio")))
);


--
-- TOC entry 243 (class 1259 OID 16959)
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.asignaciones_profesionales_id_asignacionprofesional_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5337 (class 0 OID 0)
-- Dependencies: 243
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.asignaciones_profesionales_id_asignacionprofesional_seq OWNED BY public.asignaciones_profesionales."ID_AsignacionProfesional";


--
-- TOC entry 257 (class 1259 OID 17153)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- TOC entry 256 (class 1259 OID 17152)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 17163)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- TOC entry 258 (class 1259 OID 17162)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 17143)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- TOC entry 254 (class 1259 OID 17142)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 17172)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- TOC entry 263 (class 1259 OID 17191)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- TOC entry 262 (class 1259 OID 17190)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 17171)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 17200)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- TOC entry 264 (class 1259 OID 17199)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 17261)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- TOC entry 266 (class 1259 OID 17260)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 17131)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- TOC entry 252 (class 1259 OID 17130)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 17119)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- TOC entry 250 (class 1259 OID 17118)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 17301)
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- TOC entry 228 (class 1259 OID 16813)
-- Name: especialidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.especialidades (
    "ID_Especialidad" integer CONSTRAINT especialidades_id_especialidad_not_null NOT NULL,
    "Especialidad" character varying(100) CONSTRAINT especialidades_especialidad_not_null NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 16812)
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.especialidades_id_especialidad_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5338 (class 0 OID 0)
-- Dependencies: 227
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.especialidades_id_especialidad_seq OWNED BY public.especialidades."ID_Especialidad";


--
-- TOC entry 247 (class 1259 OID 17074)
-- Name: estados_obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_obras_sociales (
    "ID_EstadoObraSocial" integer NOT NULL,
    "Descripcion" character varying(100) NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 16791)
-- Name: estados_pacientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_pacientes (
    "ID_EstadoPaciente" integer CONSTRAINT estados_pacientes_id_estadopaciente_not_null NOT NULL,
    "Estado" character varying(50) CONSTRAINT estados_pacientes_estado_not_null NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16790)
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.estados_pacientes_id_estadopaciente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5339 (class 0 OID 0)
-- Dependencies: 223
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.estados_pacientes_id_estadopaciente_seq OWNED BY public.estados_pacientes."ID_EstadoPaciente";


--
-- TOC entry 226 (class 1259 OID 16802)
-- Name: estados_turnos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_turnos (
    "ID_EstadoTurno" integer CONSTRAINT estados_turnos_id_estadoturno_not_null NOT NULL,
    "Estado" character varying(50) CONSTRAINT estados_turnos_estado_not_null NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16801)
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.estados_turnos_id_estadoturno_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5340 (class 0 OID 0)
-- Dependencies: 225
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.estados_turnos_id_estadoturno_seq OWNED BY public.estados_turnos."ID_EstadoTurno";


--
-- TOC entry 232 (class 1259 OID 16835)
-- Name: obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.obras_sociales (
    "ID_ObraSocial" integer CONSTRAINT obras_sociales_id_obrasocial_not_null NOT NULL,
    "Nombre" character varying(150) CONSTRAINT obras_sociales_nombre_not_null NOT NULL,
    "Contacto" character varying(150),
    "Mail" character varying(150),
    "Web" character varying(255),
    "ID_TipoOS" integer CONSTRAINT obras_sociales_id_tipoos_not_null NOT NULL,
    "ID_EstadoObraSocial" integer NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 16834)
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.obras_sociales_id_obrasocial_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5341 (class 0 OID 0)
-- Dependencies: 231
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.obras_sociales_id_obrasocial_seq OWNED BY public.obras_sociales."ID_ObraSocial";


--
-- TOC entry 238 (class 1259 OID 16890)
-- Name: pacientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pacientes (
    "ID_Paciente" integer CONSTRAINT pacientes_id_paciente_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT pacientes_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT pacientes_apellido_not_null NOT NULL,
    "DNI" character varying(20) CONSTRAINT pacientes_dni_not_null NOT NULL,
    "FechaNacimiento" date CONSTRAINT pacientes_fechanacimiento_not_null NOT NULL,
    "Direccion" character varying(255) NOT NULL,
    "CUD_Vencimiento" date CONSTRAINT pacientes_cud_vencimiento_not_null NOT NULL,
    "ID_ObraSocial" integer CONSTRAINT pacientes_id_obrasocial_not_null NOT NULL,
    "ID_EstadoPaciente" integer CONSTRAINT pacientes_id_estadopaciente_not_null NOT NULL,
    "Consentimiento" boolean NOT NULL,
    "NumeroAfiliado" character varying(20) NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 16889)
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pacientes_id_paciente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5342 (class 0 OID 0)
-- Dependencies: 237
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pacientes_id_paciente_seq OWNED BY public.pacientes."ID_Paciente";


--
-- TOC entry 240 (class 1259 OID 16919)
-- Name: pacientes_tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pacientes_tutores (
    "ID_PacienteTutor" integer CONSTRAINT pacientes_tutores_id_pacientetutor_not_null NOT NULL,
    "ID_Tutor" integer CONSTRAINT pacientes_tutores_id_tutor_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT pacientes_tutores_id_paciente_not_null NOT NULL,
    "ID_Parentesco" integer CONSTRAINT pacientes_tutores_id_parentesco_not_null NOT NULL,
    "ResponsablePrincipal" boolean DEFAULT false CONSTRAINT pacientes_tutores_responsableprincipal_not_null NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 16918)
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pacientes_tutores_id_pacientetutor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5343 (class 0 OID 0)
-- Dependencies: 239
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pacientes_tutores_id_pacientetutor_seq OWNED BY public.pacientes_tutores."ID_PacienteTutor";


--
-- TOC entry 220 (class 1259 OID 16769)
-- Name: parentescos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parentescos (
    "ID_Parentesco" integer CONSTRAINT parentescos_id_parentesco_not_null NOT NULL,
    "Descripcion" character varying(100) CONSTRAINT parentescos_descripcion_not_null NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16768)
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.parentescos_id_parentesco_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5344 (class 0 OID 0)
-- Dependencies: 219
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.parentescos_id_parentesco_seq OWNED BY public.parentescos."ID_Parentesco";


--
-- TOC entry 248 (class 1259 OID 17089)
-- Name: permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos (
    "ID_Permiso" integer NOT NULL,
    "Permiso" character varying(20) NOT NULL,
    "Descripcion" character varying(250) NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 16862)
-- Name: profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profesionales (
    "ID_Profesionales" integer CONSTRAINT profesionales_id_profesional_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT profesionales_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT profesionales_apellido_not_null NOT NULL,
    "DNI" character varying(20) CONSTRAINT profesionales_dni_not_null NOT NULL,
    "Matricula" character varying(50) CONSTRAINT profesionales_matricula_not_null NOT NULL,
    "ID_Especialidad" integer CONSTRAINT profesionales_id_especialidad_not_null NOT NULL,
    "Contacto" character varying(50),
    "Mail" character varying(50),
    "ID_Usuario" integer NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 16861)
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.profesionales_id_profesional_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5345 (class 0 OID 0)
-- Dependencies: 235
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.profesionales_id_profesional_seq OWNED BY public.profesionales."ID_Profesionales";


--
-- TOC entry 242 (class 1259 OID 16950)
-- Name: registros_de_sesiones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_de_sesiones (
    "ID_RegistroSesion" integer CONSTRAINT registros_de_sesiones_id_registrosesion_not_null NOT NULL,
    "NotaClinica" character varying(5000) NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 16949)
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.registros_de_sesiones_id_registrosesion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5346 (class 0 OID 0)
-- Dependencies: 241
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.registros_de_sesiones_id_registrosesion_seq OWNED BY public.registros_de_sesiones."ID_RegistroSesion";


--
-- TOC entry 230 (class 1259 OID 16824)
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    "ID_Rol" integer CONSTRAINT roles_id_rol_not_null NOT NULL,
    "Rol" character varying(50) CONSTRAINT roles_rol_not_null NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 16823)
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.roles_id_rol_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5347 (class 0 OID 0)
-- Dependencies: 229
-- Name: roles_id_rol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.roles_id_rol_seq OWNED BY public.roles."ID_Rol";


--
-- TOC entry 269 (class 1259 OID 17346)
-- Name: roles_permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_permisos (
    "ID_RolPermiso" integer NOT NULL,
    "ID_Rol" integer NOT NULL,
    "ID_Permiso" integer NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 16780)
-- Name: tipos_obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_obras_sociales (
    "ID_TipoOS" integer CONSTRAINT tipos_obras_sociales_id_tipoos_not_null NOT NULL,
    "Tipo" character varying(100) CONSTRAINT tipos_obras_sociales_tipo_not_null NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 16779)
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tipos_obras_sociales_id_tipoos_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5348 (class 0 OID 0)
-- Dependencies: 221
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tipos_obras_sociales_id_tipoos_seq OWNED BY public.tipos_obras_sociales."ID_TipoOS";


--
-- TOC entry 246 (class 1259 OID 17041)
-- Name: turnos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.turnos (
    "ID_Turnos" integer CONSTRAINT turnos_id_turno_not_null NOT NULL,
    "Fecha" date CONSTRAINT turnos_fecha_not_null NOT NULL,
    "Hora" time without time zone CONSTRAINT turnos_hora_not_null NOT NULL,
    "ID_EstadoTurno" integer CONSTRAINT turnos_id_estadoturno_not_null NOT NULL,
    "ID_RegistroSesion" integer,
    "ID_Profesional" integer CONSTRAINT turnos_id_profesional_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT turnos_id_paciente_not_null NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 17040)
-- Name: turnos_id_turno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.turnos_id_turno_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5349 (class 0 OID 0)
-- Dependencies: 245
-- Name: turnos_id_turno_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.turnos_id_turno_seq OWNED BY public.turnos."ID_Turnos";


--
-- TOC entry 234 (class 1259 OID 16852)
-- Name: tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutores (
    "ID_Tutor" integer CONSTRAINT tutores_id_tutor_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT tutores_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT tutores_apellido_not_null NOT NULL,
    "TelefonoFijo" character varying(30),
    "TelefonoMovil" character varying(30),
    "Mail" character varying(150)
);


--
-- TOC entry 233 (class 1259 OID 16851)
-- Name: tutores_id_tutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tutores_id_tutor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5350 (class 0 OID 0)
-- Dependencies: 233
-- Name: tutores_id_tutor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tutores_id_tutor_seq OWNED BY public.tutores."ID_Tutor";


--
-- TOC entry 249 (class 1259 OID 17099)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    "ID_Usuario" integer NOT NULL,
    "Usuario" character varying NOT NULL,
    "ID_Rol" integer,
    "Password" character varying NOT NULL
);


--
-- TOC entry 4999 (class 2604 OID 16963)
-- Name: asignaciones_profesionales ID_AsignacionProfesional; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales ALTER COLUMN "ID_AsignacionProfesional" SET DEFAULT nextval('public.asignaciones_profesionales_id_asignacionprofesional_seq'::regclass);


--
-- TOC entry 4990 (class 2604 OID 16816)
-- Name: especialidades ID_Especialidad; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades ALTER COLUMN "ID_Especialidad" SET DEFAULT nextval('public.especialidades_id_especialidad_seq'::regclass);


--
-- TOC entry 4988 (class 2604 OID 16794)
-- Name: estados_pacientes ID_EstadoPaciente; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes ALTER COLUMN "ID_EstadoPaciente" SET DEFAULT nextval('public.estados_pacientes_id_estadopaciente_seq'::regclass);


--
-- TOC entry 4989 (class 2604 OID 16805)
-- Name: estados_turnos ID_EstadoTurno; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos ALTER COLUMN "ID_EstadoTurno" SET DEFAULT nextval('public.estados_turnos_id_estadoturno_seq'::regclass);


--
-- TOC entry 4992 (class 2604 OID 16838)
-- Name: obras_sociales ID_ObraSocial; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales ALTER COLUMN "ID_ObraSocial" SET DEFAULT nextval('public.obras_sociales_id_obrasocial_seq'::regclass);


--
-- TOC entry 4995 (class 2604 OID 16893)
-- Name: pacientes ID_Paciente; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes ALTER COLUMN "ID_Paciente" SET DEFAULT nextval('public.pacientes_id_paciente_seq'::regclass);


--
-- TOC entry 4996 (class 2604 OID 16922)
-- Name: pacientes_tutores ID_PacienteTutor; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores ALTER COLUMN "ID_PacienteTutor" SET DEFAULT nextval('public.pacientes_tutores_id_pacientetutor_seq'::regclass);


--
-- TOC entry 4986 (class 2604 OID 16772)
-- Name: parentescos ID_Parentesco; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos ALTER COLUMN "ID_Parentesco" SET DEFAULT nextval('public.parentescos_id_parentesco_seq'::regclass);


--
-- TOC entry 4994 (class 2604 OID 16865)
-- Name: profesionales ID_Profesionales; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales ALTER COLUMN "ID_Profesionales" SET DEFAULT nextval('public.profesionales_id_profesional_seq'::regclass);


--
-- TOC entry 4998 (class 2604 OID 16953)
-- Name: registros_de_sesiones ID_RegistroSesion; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_de_sesiones ALTER COLUMN "ID_RegistroSesion" SET DEFAULT nextval('public.registros_de_sesiones_id_registrosesion_seq'::regclass);


--
-- TOC entry 4991 (class 2604 OID 16827)
-- Name: roles ID_Rol; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles ALTER COLUMN "ID_Rol" SET DEFAULT nextval('public.roles_id_rol_seq'::regclass);


--
-- TOC entry 4987 (class 2604 OID 16783)
-- Name: tipos_obras_sociales ID_TipoOS; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales ALTER COLUMN "ID_TipoOS" SET DEFAULT nextval('public.tipos_obras_sociales_id_tipoos_seq'::regclass);


--
-- TOC entry 5000 (class 2604 OID 17044)
-- Name: turnos ID_Turnos; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos ALTER COLUMN "ID_Turnos" SET DEFAULT nextval('public.turnos_id_turno_seq'::regclass);


--
-- TOC entry 4993 (class 2604 OID 16855)
-- Name: tutores ID_Tutor; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores ALTER COLUMN "ID_Tutor" SET DEFAULT nextval('public.tutores_id_tutor_seq'::regclass);


--
-- TOC entry 5306 (class 0 OID 16960)
-- Dependencies: 244
-- Data for Name: asignaciones_profesionales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.asignaciones_profesionales ("ID_AsignacionProfesional", "ID_Paciente", "ID_Profesional", "FechaInicio", "FechaFin") FROM stdin;
\.


--
-- TOC entry 5319 (class 0 OID 17153)
-- Dependencies: 257
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5321 (class 0 OID 17163)
-- Dependencies: 259
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5317 (class 0 OID 17143)
-- Dependencies: 255
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add estado obra social	7	add_estadoobrasocial
26	Can change estado obra social	7	change_estadoobrasocial
27	Can delete estado obra social	7	delete_estadoobrasocial
28	Can view estado obra social	7	view_estadoobrasocial
29	Can add estado paciente	8	add_estadopaciente
30	Can change estado paciente	8	change_estadopaciente
31	Can delete estado paciente	8	delete_estadopaciente
32	Can view estado paciente	8	view_estadopaciente
33	Can add obra social	9	add_obrasocial
34	Can change obra social	9	change_obrasocial
35	Can delete obra social	9	delete_obrasocial
36	Can view obra social	9	view_obrasocial
37	Can add paciente	10	add_paciente
38	Can change paciente	10	change_paciente
39	Can delete paciente	10	delete_paciente
40	Can view paciente	10	view_paciente
41	Can add paciente tutor	11	add_pacientetutor
42	Can change paciente tutor	11	change_pacientetutor
43	Can delete paciente tutor	11	delete_pacientetutor
44	Can view paciente tutor	11	view_pacientetutor
45	Can add parentesco	12	add_parentesco
46	Can change parentesco	12	change_parentesco
47	Can delete parentesco	12	delete_parentesco
48	Can view parentesco	12	view_parentesco
49	Can add tipo obra social	13	add_tipoobrasocial
50	Can change tipo obra social	13	change_tipoobrasocial
51	Can delete tipo obra social	13	delete_tipoobrasocial
52	Can view tipo obra social	13	view_tipoobrasocial
53	Can add tutor	14	add_tutor
54	Can change tutor	14	change_tutor
55	Can delete tutor	14	delete_tutor
56	Can view tutor	14	view_tutor
57	Can add permiso	15	add_permiso
58	Can change permiso	15	change_permiso
59	Can delete permiso	15	delete_permiso
60	Can view permiso	15	view_permiso
61	Can add rol	16	add_rol
62	Can change rol	16	change_rol
63	Can delete rol	16	delete_rol
64	Can view rol	16	view_rol
65	Can add rol permiso	17	add_rolpermiso
66	Can change rol permiso	17	change_rolpermiso
67	Can delete rol permiso	17	delete_rolpermiso
68	Can view rol permiso	17	view_rolpermiso
69	Can add usuario	18	add_usuario
70	Can change usuario	18	change_usuario
71	Can delete usuario	18	delete_usuario
72	Can view usuario	18	view_usuario
73	Can add asignacion profesional	19	add_asignacionprofesional
74	Can change asignacion profesional	19	change_asignacionprofesional
75	Can delete asignacion profesional	19	delete_asignacionprofesional
76	Can view asignacion profesional	19	view_asignacionprofesional
77	Can add especialidad	20	add_especialidad
78	Can change especialidad	20	change_especialidad
79	Can delete especialidad	20	delete_especialidad
80	Can view especialidad	20	view_especialidad
81	Can add profesional	21	add_profesional
82	Can change profesional	21	change_profesional
83	Can delete profesional	21	delete_profesional
84	Can view profesional	21	view_profesional
85	Can add estado turno	22	add_estadoturno
86	Can change estado turno	22	change_estadoturno
87	Can delete estado turno	22	delete_estadoturno
88	Can view estado turno	22	view_estadoturno
89	Can add registro sesion	23	add_registrosesion
90	Can change registro sesion	23	change_registrosesion
91	Can delete registro sesion	23	delete_registrosesion
92	Can view registro sesion	23	view_registrosesion
93	Can add turno	24	add_turno
94	Can change turno	24	change_turno
95	Can delete turno	24	delete_turno
96	Can view turno	24	view_turno
\.


--
-- TOC entry 5323 (class 0 OID 17172)
-- Dependencies: 261
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- TOC entry 5325 (class 0 OID 17191)
-- Dependencies: 263
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5327 (class 0 OID 17200)
-- Dependencies: 265
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5329 (class 0 OID 17261)
-- Dependencies: 267
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5315 (class 0 OID 17131)
-- Dependencies: 253
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	pacientes	estadoobrasocial
8	pacientes	estadopaciente
9	pacientes	obrasocial
10	pacientes	paciente
11	pacientes	pacientetutor
12	pacientes	parentesco
13	pacientes	tipoobrasocial
14	pacientes	tutor
15	usuarios	permiso
16	usuarios	rol
17	usuarios	rolpermiso
18	usuarios	usuario
19	profesionales	asignacionprofesional
20	profesionales	especialidad
21	profesionales	profesional
22	turnos	estadoturno
23	turnos	registrosesion
24	turnos	turno
\.


--
-- TOC entry 5313 (class 0 OID 17119)
-- Dependencies: 251
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-04 16:17:01.593189-03
2	auth	0001_initial	2026-09-04 16:17:01.63556-03
3	admin	0001_initial	2026-09-04 16:17:01.680545-03
4	admin	0002_logentry_remove_auto_add	2026-09-04 16:17:01.685563-03
5	admin	0003_logentry_add_action_flag_choices	2026-09-04 16:17:01.692201-03
6	contenttypes	0002_remove_content_type_name	2026-09-04 16:17:01.703275-03
7	auth	0002_alter_permission_name_max_length	2026-09-04 16:17:01.710391-03
8	auth	0003_alter_user_email_max_length	2026-09-04 16:17:01.715726-03
9	auth	0004_alter_user_username_opts	2026-09-04 16:17:01.72105-03
10	auth	0005_alter_user_last_login_null	2026-09-04 16:17:01.729231-03
11	auth	0006_require_contenttypes_0002	2026-09-04 16:17:01.730177-03
12	auth	0007_alter_validators_add_error_messages	2026-09-04 16:17:01.735125-03
13	auth	0008_alter_user_username_max_length	2026-09-04 16:17:01.745395-03
14	auth	0009_alter_user_last_name_max_length	2026-09-04 16:17:01.754309-03
15	auth	0010_alter_group_name_max_length	2026-09-04 16:17:01.763783-03
16	auth	0011_update_proxy_permissions	2026-09-04 16:17:01.775928-03
17	auth	0012_alter_user_first_name_max_length	2026-09-04 16:17:01.787677-03
18	sessions	0001_initial	2026-09-04 16:17:01.808238-03
19	pacientes	0001_initial	2026-09-07 17:13:45.120824-03
20	profesionales	0001_initial	2026-09-07 17:13:45.124764-03
21	turnos	0001_initial	2026-09-07 17:13:45.126818-03
22	usuarios	0001_initial	2026-09-07 17:13:45.129718-03
\.


--
-- TOC entry 5330 (class 0 OID 17301)
-- Dependencies: 268
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- TOC entry 5290 (class 0 OID 16813)
-- Dependencies: 228
-- Data for Name: especialidades; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.especialidades ("ID_Especialidad", "Especialidad") FROM stdin;
\.


--
-- TOC entry 5309 (class 0 OID 17074)
-- Dependencies: 247
-- Data for Name: estados_obras_sociales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_obras_sociales ("ID_EstadoObraSocial", "Descripcion") FROM stdin;
\.


--
-- TOC entry 5286 (class 0 OID 16791)
-- Dependencies: 224
-- Data for Name: estados_pacientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_pacientes ("ID_EstadoPaciente", "Estado") FROM stdin;
1	Activo
2	Inactivo
\.


--
-- TOC entry 5288 (class 0 OID 16802)
-- Dependencies: 226
-- Data for Name: estados_turnos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.estados_turnos ("ID_EstadoTurno", "Estado") FROM stdin;
1	Pendiente
2	Confirmado
3	Cancelado
4	Realizado
\.


--
-- TOC entry 5294 (class 0 OID 16835)
-- Dependencies: 232
-- Data for Name: obras_sociales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.obras_sociales ("ID_ObraSocial", "Nombre", "Contacto", "Mail", "Web", "ID_TipoOS", "ID_EstadoObraSocial") FROM stdin;
\.


--
-- TOC entry 5300 (class 0 OID 16890)
-- Dependencies: 238
-- Data for Name: pacientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pacientes ("ID_Paciente", "Nombre", "Apellido", "DNI", "FechaNacimiento", "Direccion", "CUD_Vencimiento", "ID_ObraSocial", "ID_EstadoPaciente", "Consentimiento", "NumeroAfiliado") FROM stdin;
\.


--
-- TOC entry 5302 (class 0 OID 16919)
-- Dependencies: 240
-- Data for Name: pacientes_tutores; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pacientes_tutores ("ID_PacienteTutor", "ID_Tutor", "ID_Paciente", "ID_Parentesco", "ResponsablePrincipal") FROM stdin;
\.


--
-- TOC entry 5282 (class 0 OID 16769)
-- Dependencies: 220
-- Data for Name: parentescos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.parentescos ("ID_Parentesco", "Descripcion") FROM stdin;
\.


--
-- TOC entry 5310 (class 0 OID 17089)
-- Dependencies: 248
-- Data for Name: permisos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.permisos ("ID_Permiso", "Permiso", "Descripcion") FROM stdin;
\.


--
-- TOC entry 5298 (class 0 OID 16862)
-- Dependencies: 236
-- Data for Name: profesionales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profesionales ("ID_Profesionales", "Nombre", "Apellido", "DNI", "Matricula", "ID_Especialidad", "Contacto", "Mail", "ID_Usuario") FROM stdin;
\.


--
-- TOC entry 5304 (class 0 OID 16950)
-- Dependencies: 242
-- Data for Name: registros_de_sesiones; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.registros_de_sesiones ("ID_RegistroSesion", "NotaClinica") FROM stdin;
\.


--
-- TOC entry 5292 (class 0 OID 16824)
-- Dependencies: 230
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles ("ID_Rol", "Rol") FROM stdin;
1	Administrador
2	Profesional
\.


--
-- TOC entry 5331 (class 0 OID 17346)
-- Dependencies: 269
-- Data for Name: roles_permisos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles_permisos ("ID_RolPermiso", "ID_Rol", "ID_Permiso") FROM stdin;
\.


--
-- TOC entry 5284 (class 0 OID 16780)
-- Dependencies: 222
-- Data for Name: tipos_obras_sociales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tipos_obras_sociales ("ID_TipoOS", "Tipo") FROM stdin;
\.


--
-- TOC entry 5308 (class 0 OID 17041)
-- Dependencies: 246
-- Data for Name: turnos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.turnos ("ID_Turnos", "Fecha", "Hora", "ID_EstadoTurno", "ID_RegistroSesion", "ID_Profesional", "ID_Paciente") FROM stdin;
\.


--
-- TOC entry 5296 (class 0 OID 16852)
-- Dependencies: 234
-- Data for Name: tutores; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tutores ("ID_Tutor", "Nombre", "Apellido", "TelefonoFijo", "TelefonoMovil", "Mail") FROM stdin;
\.


--
-- TOC entry 5311 (class 0 OID 17099)
-- Dependencies: 249
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios ("ID_Usuario", "Usuario", "ID_Rol", "Password") FROM stdin;
\.


--
-- TOC entry 5351 (class 0 OID 0)
-- Dependencies: 243
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.asignaciones_profesionales_id_asignacionprofesional_seq', 1, false);


--
-- TOC entry 5352 (class 0 OID 0)
-- Dependencies: 256
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5353 (class 0 OID 0)
-- Dependencies: 258
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5354 (class 0 OID 0)
-- Dependencies: 254
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 96, true);


--
-- TOC entry 5355 (class 0 OID 0)
-- Dependencies: 262
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5356 (class 0 OID 0)
-- Dependencies: 260
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- TOC entry 5357 (class 0 OID 0)
-- Dependencies: 264
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5358 (class 0 OID 0)
-- Dependencies: 266
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5359 (class 0 OID 0)
-- Dependencies: 252
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 24, true);


--
-- TOC entry 5360 (class 0 OID 0)
-- Dependencies: 250
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- TOC entry 5361 (class 0 OID 0)
-- Dependencies: 227
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.especialidades_id_especialidad_seq', 1, false);


--
-- TOC entry 5362 (class 0 OID 0)
-- Dependencies: 223
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estados_pacientes_id_estadopaciente_seq', 2, true);


--
-- TOC entry 5363 (class 0 OID 0)
-- Dependencies: 225
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.estados_turnos_id_estadoturno_seq', 4, true);


--
-- TOC entry 5364 (class 0 OID 0)
-- Dependencies: 231
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.obras_sociales_id_obrasocial_seq', 1, false);


--
-- TOC entry 5365 (class 0 OID 0)
-- Dependencies: 237
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pacientes_id_paciente_seq', 1, false);


--
-- TOC entry 5366 (class 0 OID 0)
-- Dependencies: 239
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pacientes_tutores_id_pacientetutor_seq', 1, false);


--
-- TOC entry 5367 (class 0 OID 0)
-- Dependencies: 219
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.parentescos_id_parentesco_seq', 1, false);


--
-- TOC entry 5368 (class 0 OID 0)
-- Dependencies: 235
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.profesionales_id_profesional_seq', 1, false);


--
-- TOC entry 5369 (class 0 OID 0)
-- Dependencies: 241
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.registros_de_sesiones_id_registrosesion_seq', 1, false);


--
-- TOC entry 5370 (class 0 OID 0)
-- Dependencies: 229
-- Name: roles_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_id_rol_seq', 2, true);


--
-- TOC entry 5371 (class 0 OID 0)
-- Dependencies: 221
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tipos_obras_sociales_id_tipoos_seq', 1, false);


--
-- TOC entry 5372 (class 0 OID 0)
-- Dependencies: 245
-- Name: turnos_id_turno_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.turnos_id_turno_seq', 1, false);


--
-- TOC entry 5373 (class 0 OID 0)
-- Dependencies: 233
-- Name: tutores_id_tutor_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tutores_id_tutor_seq', 1, false);


--
-- TOC entry 5032 (class 2606 OID 17367)
-- Name: profesionales UQ_Profesionales_ID_Usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT "UQ_Profesionales_ID_Usuario" UNIQUE ("ID_Usuario");


--
-- TOC entry 5109 (class 2606 OID 17361)
-- Name: roles_permisos UQ_RolesPermisos_Rol_Permiso; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT "UQ_RolesPermisos_Rol_Permiso" UNIQUE ("ID_Rol", "ID_Permiso");


--
-- TOC entry 5052 (class 2606 OID 16970)
-- Name: asignaciones_profesionales asignaciones_profesionales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT asignaciones_profesionales_pkey PRIMARY KEY ("ID_AsignacionProfesional");


--
-- TOC entry 5074 (class 2606 OID 17297)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 5079 (class 2606 OID 17218)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 5082 (class 2606 OID 17170)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5076 (class 2606 OID 17159)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 5069 (class 2606 OID 17209)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 5071 (class 2606 OID 17151)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5090 (class 2606 OID 17198)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5093 (class 2606 OID 17233)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5084 (class 2606 OID 17187)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5096 (class 2606 OID 17207)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5099 (class 2606 OID 17247)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5087 (class 2606 OID 17290)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 5102 (class 2606 OID 17274)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5064 (class 2606 OID 17141)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 5066 (class 2606 OID 17139)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5062 (class 2606 OID 17129)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5106 (class 2606 OID 17310)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5020 (class 2606 OID 16822)
-- Name: especialidades especialidades_especialidad_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades
    ADD CONSTRAINT especialidades_especialidad_key UNIQUE ("Especialidad");


--
-- TOC entry 5022 (class 2606 OID 16820)
-- Name: especialidades especialidades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades
    ADD CONSTRAINT especialidades_pkey PRIMARY KEY ("ID_Especialidad");


--
-- TOC entry 5012 (class 2606 OID 16800)
-- Name: estados_pacientes estados_pacientes_estado_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes
    ADD CONSTRAINT estados_pacientes_estado_key UNIQUE ("Estado");


--
-- TOC entry 5014 (class 2606 OID 16798)
-- Name: estados_pacientes estados_pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes
    ADD CONSTRAINT estados_pacientes_pkey PRIMARY KEY ("ID_EstadoPaciente");


--
-- TOC entry 5016 (class 2606 OID 16811)
-- Name: estados_turnos estados_turnos_estado_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos
    ADD CONSTRAINT estados_turnos_estado_key UNIQUE ("Estado");


--
-- TOC entry 5018 (class 2606 OID 16809)
-- Name: estados_turnos estados_turnos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos
    ADD CONSTRAINT estados_turnos_pkey PRIMARY KEY ("ID_EstadoTurno");


--
-- TOC entry 5028 (class 2606 OID 16845)
-- Name: obras_sociales obras_sociales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales
    ADD CONSTRAINT obras_sociales_pkey PRIMARY KEY ("ID_ObraSocial");


--
-- TOC entry 5040 (class 2606 OID 16907)
-- Name: pacientes pacientes_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_dni_key UNIQUE ("DNI");


--
-- TOC entry 5042 (class 2606 OID 16905)
-- Name: pacientes pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_pkey PRIMARY KEY ("ID_Paciente");


--
-- TOC entry 5044 (class 2606 OID 16930)
-- Name: pacientes_tutores pacientes_tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT pacientes_tutores_pkey PRIMARY KEY ("ID_PacienteTutor");


--
-- TOC entry 5004 (class 2606 OID 16778)
-- Name: parentescos parentescos_descripcion_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos
    ADD CONSTRAINT parentescos_descripcion_key UNIQUE ("Descripcion");


--
-- TOC entry 5006 (class 2606 OID 16776)
-- Name: parentescos parentescos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos
    ADD CONSTRAINT parentescos_pkey PRIMARY KEY ("ID_Parentesco");


--
-- TOC entry 5034 (class 2606 OID 16876)
-- Name: profesionales profesionales_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_dni_key UNIQUE ("DNI");


--
-- TOC entry 5036 (class 2606 OID 16878)
-- Name: profesionales profesionales_matricula_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_matricula_key UNIQUE ("Matricula");


--
-- TOC entry 5038 (class 2606 OID 16874)
-- Name: profesionales profesionales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_pkey PRIMARY KEY ("ID_Profesionales");


--
-- TOC entry 5050 (class 2606 OID 16958)
-- Name: registros_de_sesiones registros_de_sesiones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_de_sesiones
    ADD CONSTRAINT registros_de_sesiones_pkey PRIMARY KEY ("ID_RegistroSesion");


--
-- TOC entry 5024 (class 2606 OID 16831)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY ("ID_Rol");


--
-- TOC entry 5026 (class 2606 OID 16833)
-- Name: roles roles_rol_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_rol_key UNIQUE ("Rol");


--
-- TOC entry 5008 (class 2606 OID 16787)
-- Name: tipos_obras_sociales tipos_obras_sociales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales
    ADD CONSTRAINT tipos_obras_sociales_pkey PRIMARY KEY ("ID_TipoOS");


--
-- TOC entry 5010 (class 2606 OID 16789)
-- Name: tipos_obras_sociales tipos_obras_sociales_tipo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales
    ADD CONSTRAINT tipos_obras_sociales_tipo_key UNIQUE ("Tipo");


--
-- TOC entry 5054 (class 2606 OID 17052)
-- Name: turnos turnos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT turnos_pkey PRIMARY KEY ("ID_Turnos");


--
-- TOC entry 5030 (class 2606 OID 16860)
-- Name: tutores tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores
    ADD CONSTRAINT tutores_pkey PRIMARY KEY ("ID_Tutor");


--
-- TOC entry 5048 (class 2606 OID 16932)
-- Name: pacientes_tutores uq_paciente_tutor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT uq_paciente_tutor UNIQUE ("ID_Paciente", "ID_Tutor");


--
-- TOC entry 5058 (class 2606 OID 17378)
-- Name: usuarios uq_usuarios_usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uq_usuarios_usuario UNIQUE ("Usuario");


--
-- TOC entry 5060 (class 2606 OID 17388)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY ("ID_Usuario");


--
-- TOC entry 5072 (class 1259 OID 17298)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 5077 (class 1259 OID 17229)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 5080 (class 1259 OID 17230)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 5067 (class 1259 OID 17215)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5088 (class 1259 OID 17245)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 5091 (class 1259 OID 17244)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 5094 (class 1259 OID 17259)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5097 (class 1259 OID 17258)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 5085 (class 1259 OID 17291)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5100 (class 1259 OID 17285)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5103 (class 1259 OID 17286)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5104 (class 1259 OID 17312)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5107 (class 1259 OID 17311)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5045 (class 1259 OID 17379)
-- Name: uq_paciente_responsable_principal; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_paciente_responsable_principal ON public.pacientes_tutores USING btree ("ID_Paciente") WHERE ("ResponsablePrincipal" = true);


--
-- TOC entry 5046 (class 1259 OID 16948)
-- Name: uq_paciente_responsableprincipal; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_paciente_responsableprincipal ON public.pacientes_tutores USING btree ("ID_Paciente") WHERE ("ResponsablePrincipal" = true);


--
-- TOC entry 5055 (class 1259 OID 17380)
-- Name: uq_turno_profesional_fecha_hora; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_turno_profesional_fecha_hora ON public.turnos USING btree ("ID_Profesional", "Fecha", "Hora");


--
-- TOC entry 5056 (class 1259 OID 17381)
-- Name: uq_turno_registro_sesion; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_turno_registro_sesion ON public.turnos USING btree ("ID_RegistroSesion") WHERE ("ID_RegistroSesion" IS NOT NULL);


--
-- TOC entry 5126 (class 2606 OID 17224)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5127 (class 2606 OID 17219)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5125 (class 2606 OID 17210)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5128 (class 2606 OID 17239)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5129 (class 2606 OID 17234)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5130 (class 2606 OID 17253)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5131 (class 2606 OID 17248)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5132 (class 2606 OID 17275)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5133 (class 2606 OID 17280)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5118 (class 2606 OID 16971)
-- Name: asignaciones_profesionales fk_asignacionesprofesionales_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT fk_asignacionesprofesionales_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente");


--
-- TOC entry 5119 (class 2606 OID 16976)
-- Name: asignaciones_profesionales fk_asignacionesprofesionales_profesional; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT fk_asignacionesprofesionales_profesional FOREIGN KEY ("ID_Profesional") REFERENCES public.profesionales("ID_Profesionales");


--
-- TOC entry 5110 (class 2606 OID 16846)
-- Name: obras_sociales fk_obrassociales_tipos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales
    ADD CONSTRAINT fk_obrassociales_tipos FOREIGN KEY ("ID_TipoOS") REFERENCES public.tipos_obras_sociales("ID_TipoOS");


--
-- TOC entry 5113 (class 2606 OID 16913)
-- Name: pacientes fk_pacientes_estados; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT fk_pacientes_estados FOREIGN KEY ("ID_EstadoPaciente") REFERENCES public.estados_pacientes("ID_EstadoPaciente");


--
-- TOC entry 5114 (class 2606 OID 16908)
-- Name: pacientes fk_pacientes_obrassociales; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT fk_pacientes_obrassociales FOREIGN KEY ("ID_ObraSocial") REFERENCES public.obras_sociales("ID_ObraSocial");


--
-- TOC entry 5115 (class 2606 OID 16938)
-- Name: pacientes_tutores fk_pacientestutores_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente") ON DELETE CASCADE;


--
-- TOC entry 5116 (class 2606 OID 16943)
-- Name: pacientes_tutores fk_pacientestutores_parentesco; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_parentesco FOREIGN KEY ("ID_Parentesco") REFERENCES public.parentescos("ID_Parentesco");


--
-- TOC entry 5117 (class 2606 OID 16933)
-- Name: pacientes_tutores fk_pacientestutores_tutor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_tutor FOREIGN KEY ("ID_Tutor") REFERENCES public.tutores("ID_Tutor") ON DELETE CASCADE;


--
-- TOC entry 5111 (class 2606 OID 16879)
-- Name: profesionales fk_profesionales_especialidades; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_especialidades FOREIGN KEY ("ID_Especialidad") REFERENCES public.especialidades("ID_Especialidad");


--
-- TOC entry 5112 (class 2606 OID 17394)
-- Name: profesionales fk_profesionales_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_usuario FOREIGN KEY ("ID_Usuario") REFERENCES public.usuarios("ID_Usuario");


--
-- TOC entry 5120 (class 2606 OID 17053)
-- Name: turnos fk_turnos_estados; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_estados FOREIGN KEY ("ID_EstadoTurno") REFERENCES public.estados_turnos("ID_EstadoTurno");


--
-- TOC entry 5121 (class 2606 OID 17068)
-- Name: turnos fk_turnos_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente");


--
-- TOC entry 5122 (class 2606 OID 17063)
-- Name: turnos fk_turnos_profesional; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_profesional FOREIGN KEY ("ID_Profesional") REFERENCES public.profesionales("ID_Profesionales");


--
-- TOC entry 5123 (class 2606 OID 17058)
-- Name: turnos fk_turnos_registrosesion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_registrosesion FOREIGN KEY ("ID_RegistroSesion") REFERENCES public.registros_de_sesiones("ID_RegistroSesion") ON DELETE SET NULL;


--
-- TOC entry 5124 (class 2606 OID 17389)
-- Name: usuarios fk_usuarios_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_rol FOREIGN KEY ("ID_Rol") REFERENCES public.roles("ID_Rol");


-- Completed on 2026-09-07 17:16:37

--
-- PostgreSQL database dump complete
--

\unrestrict Oh7mZY3Dle1DrhdRKooctAjdBGc2uxhOcmKxxl8w8blFYDngeenFdeVObILjOOJ

