# Generated by Django 6.1.1 on 2026-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTurno',
            fields=[
                ('id_estado_turno', models.AutoField(db_column='ID_EstadoTurno', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
            ],
            options={
                'db_table': 'estados_turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroSesion',
            fields=[
                ('id_registro_sesion', models.AutoField(db_column='ID_RegistroSesion', primary_key=True, serialize=False)),
                ('nota_clinica', models.CharField(db_column='NotaClinica', max_length=5000)),
            ],
            options={
                'db_table': 'registros_de_sesiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(db_column='ID_Turnos', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
    ]
