# Generated by Django 6.1.1 on 2026-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoObraSocial',
            fields=[
                ('id_estado_obra_social', models.AutoField(db_column='ID_EstadoObraSocial', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'estados_obras_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPaciente',
            fields=[
                ('id_estado_paciente', models.AutoField(db_column='ID_EstadoPaciente', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
            ],
            options={
                'db_table': 'estados_pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id_obra_social', models.AutoField(db_column='ID_ObraSocial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=150, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=150, null=True)),
                ('web', models.CharField(blank=True, db_column='Web', max_length=255, null=True)),
            ],
            options={
                'db_table': 'obras_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(db_column='ID_Paciente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('dni', models.CharField(db_column='DNI', max_length=20)),
                ('fecha_nacimiento', models.DateField(db_column='FechaNacimiento')),
                ('direccion', models.CharField(db_column='Direccion', max_length=255)),
                ('consentimiento', models.BooleanField(db_column='Consentimiento')),
                ('cud_vencimiento', models.DateField(db_column='CUD_Vencimiento')),
                ('numero_afiliado', models.CharField(db_column='NumeroAfiliado', max_length=20)),
            ],
            options={
                'db_table': 'pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacienteTutor',
            fields=[
                ('id_paciente_tutor', models.AutoField(db_column='ID_PacienteTutor', primary_key=True, serialize=False)),
                ('responsable_principal', models.BooleanField(db_column='ResponsablePrincipal')),
            ],
            options={
                'db_table': 'pacientes_tutores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(db_column='ID_Parentesco', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'parentescos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoObraSocial',
            fields=[
                ('id_tipo_os', models.AutoField(db_column='ID_TipoOS', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=100)),
            ],
            options={
                'db_table': 'tipos_obras_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(db_column='ID_Tutor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('telefono_fijo', models.CharField(db_column='TelefonoFijo', max_length=30)),
                ('telefono_movil', models.CharField(db_column='TelefonoMovil', max_length=30)),
                ('mail', models.CharField(db_column='Mail', max_length=150)),
            ],
            options={
                'db_table': 'tutores',
                'managed': False,
            },
        ),
    ]
