--
-- PostgreSQL database dump
--

\restrict wCyt4KEMGHEjKsrzC5ODss8b249UFkShbL4PsaU0u3YzrUE9uTCP3xgXEJ7gFrz

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asignaciones_profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asignaciones_profesionales (
    "ID_AsignacionProfesional" integer CONSTRAINT asignaciones_profesionales_id_asignacionprofesional_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT asignaciones_profesionales_id_paciente_not_null NOT NULL,
    "ID_Profesional" integer CONSTRAINT asignaciones_profesionales_id_profesional_not_null NOT NULL,
    "FechaInicio" date CONSTRAINT asignaciones_profesionales_fechainicio_not_null NOT NULL,
    "FechaFin" date,
    CONSTRAINT ck_asignacionesprofesionales_fechas CHECK ((("FechaFin" IS NULL) OR ("FechaFin" >= "FechaInicio")))
);


--
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.asignaciones_profesionales_id_asignacionprofesional_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: asignaciones_profesionales_id_asignacionprofesional_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.asignaciones_profesionales_id_asignacionprofesional_seq OWNED BY public.asignaciones_profesionales."ID_AsignacionProfesional";


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: especialidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.especialidades (
    "ID_Especialidad" integer CONSTRAINT especialidades_id_especialidad_not_null NOT NULL,
    "Especialidad" character varying(100) CONSTRAINT especialidades_especialidad_not_null NOT NULL
);


--
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.especialidades_id_especialidad_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: especialidades_id_especialidad_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.especialidades_id_especialidad_seq OWNED BY public.especialidades."ID_Especialidad";


--
-- Name: estados_obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_obras_sociales (
    "ID_EstadoObraSocial" integer NOT NULL,
    "Descripcion" character varying(100)
);


--
-- Name: estados_pacientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_pacientes (
    "ID_EstadoPaciente" integer CONSTRAINT estados_pacientes_id_estadopaciente_not_null NOT NULL,
    "Estado" character varying(100) CONSTRAINT estados_pacientes_estado_not_null NOT NULL
);


--
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.estados_pacientes_id_estadopaciente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: estados_pacientes_id_estadopaciente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.estados_pacientes_id_estadopaciente_seq OWNED BY public.estados_pacientes."ID_EstadoPaciente";


--
-- Name: estados_profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_profesionales (
    "ID_EstadoProfesional" integer NOT NULL,
    "Estado" character varying(100) NOT NULL
);


--
-- Name: estados_turnos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estados_turnos (
    "ID_EstadoTurno" integer CONSTRAINT estados_turnos_id_estadoturno_not_null NOT NULL,
    "Estado" character varying(50) CONSTRAINT estados_turnos_estado_not_null NOT NULL
);


--
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.estados_turnos_id_estadoturno_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: estados_turnos_id_estadoturno_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.estados_turnos_id_estadoturno_seq OWNED BY public.estados_turnos."ID_EstadoTurno";


--
-- Name: obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.obras_sociales (
    "ID_ObraSocial" integer CONSTRAINT obras_sociales_id_obrasocial_not_null NOT NULL,
    "Nombre" character varying(150) CONSTRAINT obras_sociales_nombre_not_null NOT NULL,
    "Contacto" character varying(150),
    "Mail" character varying(150),
    "Web" character varying(255),
    "ID_TipoOS" integer CONSTRAINT obras_sociales_id_tipoos_not_null NOT NULL,
    "ID_EstadoObraSocial" integer NOT NULL
);


--
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.obras_sociales_id_obrasocial_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: obras_sociales_id_obrasocial_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.obras_sociales_id_obrasocial_seq OWNED BY public.obras_sociales."ID_ObraSocial";


--
-- Name: pacientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pacientes (
    "ID_Paciente" integer CONSTRAINT pacientes_id_paciente_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT pacientes_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT pacientes_apellido_not_null NOT NULL,
    "DNI" character varying(20) CONSTRAINT pacientes_dni_not_null NOT NULL,
    "FechaNacimiento" date CONSTRAINT pacientes_fechanacimiento_not_null NOT NULL,
    "Direccion" character varying(255) NOT NULL,
    "CUD_Vencimiento" date CONSTRAINT pacientes_cud_vencimiento_not_null NOT NULL,
    "ID_ObraSocial" integer CONSTRAINT pacientes_id_obrasocial_not_null NOT NULL,
    "ID_EstadoPaciente" integer CONSTRAINT pacientes_id_estadopaciente_not_null NOT NULL,
    "Consentimiento" boolean NOT NULL,
    "NumeroAfiliado" character varying(20) NOT NULL,
    "Mail" character varying(50),
    "CUD_Numero" character varying(20)
);


--
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pacientes_id_paciente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pacientes_id_paciente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pacientes_id_paciente_seq OWNED BY public.pacientes."ID_Paciente";


--
-- Name: pacientes_tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pacientes_tutores (
    "ID_PacienteTutor" integer CONSTRAINT pacientes_tutores_id_pacientetutor_not_null NOT NULL,
    "ID_Tutor" integer CONSTRAINT pacientes_tutores_id_tutor_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT pacientes_tutores_id_paciente_not_null NOT NULL,
    "ID_Parentesco" integer CONSTRAINT pacientes_tutores_id_parentesco_not_null NOT NULL,
    "ResponsablePrincipal" boolean DEFAULT false CONSTRAINT pacientes_tutores_responsableprincipal_not_null NOT NULL
);


--
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pacientes_tutores_id_pacientetutor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pacientes_tutores_id_pacientetutor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pacientes_tutores_id_pacientetutor_seq OWNED BY public.pacientes_tutores."ID_PacienteTutor";


--
-- Name: parentescos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parentescos (
    "ID_Parentesco" integer CONSTRAINT parentescos_id_parentesco_not_null NOT NULL,
    "Descripcion" character varying(100) CONSTRAINT parentescos_descripcion_not_null NOT NULL
);


--
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.parentescos_id_parentesco_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: parentescos_id_parentesco_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.parentescos_id_parentesco_seq OWNED BY public.parentescos."ID_Parentesco";


--
-- Name: permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permisos (
    "ID_Permiso" integer NOT NULL,
    "Permiso" character varying(20) NOT NULL,
    "Descripcion" character varying(250) NOT NULL
);


--
-- Name: permisos_ID_Permiso_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permisos ALTER COLUMN "ID_Permiso" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."permisos_ID_Permiso_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profesionales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profesionales (
    "ID_Profesionales" integer CONSTRAINT profesionales_id_profesional_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT profesionales_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT profesionales_apellido_not_null NOT NULL,
    "DNI" character varying(20) CONSTRAINT profesionales_dni_not_null NOT NULL,
    "Matricula" character varying(50) CONSTRAINT profesionales_matricula_not_null NOT NULL,
    "ID_Especialidad" integer CONSTRAINT profesionales_id_especialidad_not_null NOT NULL,
    "Contacto" character varying(50),
    "Mail" character varying(50),
    "ID_Usuario" integer NOT NULL,
    "ID_EstadoProfesional" integer NOT NULL,
    "ID_Rol" integer
);


--
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.profesionales_id_profesional_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: profesionales_id_profesional_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.profesionales_id_profesional_seq OWNED BY public.profesionales."ID_Profesionales";


--
-- Name: registros_de_sesiones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_de_sesiones (
    "ID_RegistroSesion" integer CONSTRAINT registros_de_sesiones_id_registrosesion_not_null NOT NULL,
    "TrabajoSesion" character varying(225) NOT NULL,
    "Resultado" character varying(225) NOT NULL,
    "NotaEspecial" character varying(225) NOT NULL
);


--
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.registros_de_sesiones_id_registrosesion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: registros_de_sesiones_id_registrosesion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.registros_de_sesiones_id_registrosesion_seq OWNED BY public.registros_de_sesiones."ID_RegistroSesion";


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    "ID_Rol" integer CONSTRAINT roles_id_rol_not_null NOT NULL,
    "Rol" character varying(50) CONSTRAINT roles_rol_not_null NOT NULL
);


--
-- Name: roles_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.roles_id_rol_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: roles_id_rol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.roles_id_rol_seq OWNED BY public.roles."ID_Rol";


--
-- Name: roles_permisos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles_permisos (
    "ID_RolPermiso" integer NOT NULL,
    "ID_Rol" integer NOT NULL,
    "ID_Permiso" integer NOT NULL
);


--
-- Name: roles_permisos_ID_RolPermiso_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles_permisos ALTER COLUMN "ID_RolPermiso" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."roles_permisos_ID_RolPermiso_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_obras_sociales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_obras_sociales (
    "ID_TipoOS" integer CONSTRAINT tipos_obras_sociales_id_tipoos_not_null NOT NULL,
    "Tipo" character varying(100) CONSTRAINT tipos_obras_sociales_tipo_not_null NOT NULL
);


--
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tipos_obras_sociales_id_tipoos_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tipos_obras_sociales_id_tipoos_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tipos_obras_sociales_id_tipoos_seq OWNED BY public.tipos_obras_sociales."ID_TipoOS";


--
-- Name: turnos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.turnos (
    "ID_Turnos" integer CONSTRAINT turnos_id_turno_not_null NOT NULL,
    "Fecha" date CONSTRAINT turnos_fecha_not_null NOT NULL,
    "Hora" time without time zone CONSTRAINT turnos_hora_not_null NOT NULL,
    "ID_EstadoTurno" integer CONSTRAINT turnos_id_estadoturno_not_null NOT NULL,
    "ID_RegistroSesion" integer,
    "ID_Profesional" integer CONSTRAINT turnos_id_profesional_not_null NOT NULL,
    "ID_Paciente" integer CONSTRAINT turnos_id_paciente_not_null NOT NULL
);


--
-- Name: turnos_id_turno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.turnos_id_turno_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: turnos_id_turno_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.turnos_id_turno_seq OWNED BY public.turnos."ID_Turnos";


--
-- Name: tutores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tutores (
    "ID_Tutor" integer CONSTRAINT tutores_id_tutor_not_null NOT NULL,
    "Nombre" character varying(100) CONSTRAINT tutores_nombre_not_null NOT NULL,
    "Apellido" character varying(100) CONSTRAINT tutores_apellido_not_null NOT NULL,
    "Telefono" character varying(30),
    "Movil" character varying(30),
    "Mail" character varying(150),
    "DNI" character varying(20),
    "Domicilio" character varying(225)
);


--
-- Name: tutores_id_tutor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tutores_id_tutor_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tutores_id_tutor_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tutores_id_tutor_seq OWNED BY public.tutores."ID_Tutor";


--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    "ID_Usuario" integer DEFAULT nextval('public.usuarios_id_usuario_seq'::regclass) NOT NULL,
    "Usuario" character varying(100) NOT NULL,
    "ID_Rol" integer,
    "Password" character varying NOT NULL,
    "Activo" boolean DEFAULT true CONSTRAINT usuarios_activo_not_null NOT NULL
);


--
-- Name: asignaciones_profesionales ID_AsignacionProfesional; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales ALTER COLUMN "ID_AsignacionProfesional" SET DEFAULT nextval('public.asignaciones_profesionales_id_asignacionprofesional_seq'::regclass);


--
-- Name: especialidades ID_Especialidad; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades ALTER COLUMN "ID_Especialidad" SET DEFAULT nextval('public.especialidades_id_especialidad_seq'::regclass);


--
-- Name: estados_pacientes ID_EstadoPaciente; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes ALTER COLUMN "ID_EstadoPaciente" SET DEFAULT nextval('public.estados_pacientes_id_estadopaciente_seq'::regclass);


--
-- Name: estados_turnos ID_EstadoTurno; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos ALTER COLUMN "ID_EstadoTurno" SET DEFAULT nextval('public.estados_turnos_id_estadoturno_seq'::regclass);


--
-- Name: obras_sociales ID_ObraSocial; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales ALTER COLUMN "ID_ObraSocial" SET DEFAULT nextval('public.obras_sociales_id_obrasocial_seq'::regclass);


--
-- Name: pacientes ID_Paciente; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes ALTER COLUMN "ID_Paciente" SET DEFAULT nextval('public.pacientes_id_paciente_seq'::regclass);


--
-- Name: pacientes_tutores ID_PacienteTutor; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores ALTER COLUMN "ID_PacienteTutor" SET DEFAULT nextval('public.pacientes_tutores_id_pacientetutor_seq'::regclass);


--
-- Name: parentescos ID_Parentesco; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos ALTER COLUMN "ID_Parentesco" SET DEFAULT nextval('public.parentescos_id_parentesco_seq'::regclass);


--
-- Name: profesionales ID_Profesionales; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales ALTER COLUMN "ID_Profesionales" SET DEFAULT nextval('public.profesionales_id_profesional_seq'::regclass);


--
-- Name: registros_de_sesiones ID_RegistroSesion; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_de_sesiones ALTER COLUMN "ID_RegistroSesion" SET DEFAULT nextval('public.registros_de_sesiones_id_registrosesion_seq'::regclass);


--
-- Name: roles ID_Rol; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles ALTER COLUMN "ID_Rol" SET DEFAULT nextval('public.roles_id_rol_seq'::regclass);


--
-- Name: tipos_obras_sociales ID_TipoOS; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales ALTER COLUMN "ID_TipoOS" SET DEFAULT nextval('public.tipos_obras_sociales_id_tipoos_seq'::regclass);


--
-- Name: turnos ID_Turnos; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos ALTER COLUMN "ID_Turnos" SET DEFAULT nextval('public.turnos_id_turno_seq'::regclass);


--
-- Name: tutores ID_Tutor; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores ALTER COLUMN "ID_Tutor" SET DEFAULT nextval('public.tutores_id_tutor_seq'::regclass);


--
-- Name: profesionales UQ_Profesionales_ID_Usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT "UQ_Profesionales_ID_Usuario" UNIQUE ("ID_Usuario");


--
-- Name: roles_permisos UQ_RolesPermisos_Rol_Permiso; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT "UQ_RolesPermisos_Rol_Permiso" UNIQUE ("ID_Rol", "ID_Permiso");


--
-- Name: tutores UQ_Tutores_DNI; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores
    ADD CONSTRAINT "UQ_Tutores_DNI" UNIQUE ("DNI");


--
-- Name: asignaciones_profesionales asignaciones_profesionales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT asignaciones_profesionales_pkey PRIMARY KEY ("ID_AsignacionProfesional");


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: especialidades especialidades_especialidad_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades
    ADD CONSTRAINT especialidades_especialidad_key UNIQUE ("Especialidad");


--
-- Name: especialidades especialidades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidades
    ADD CONSTRAINT especialidades_pkey PRIMARY KEY ("ID_Especialidad");


--
-- Name: estados_obras_sociales estados_obras_sociales_descripcion_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_obras_sociales
    ADD CONSTRAINT estados_obras_sociales_descripcion_key UNIQUE ("Descripcion");


--
-- Name: estados_obras_sociales estados_obras_sociales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_obras_sociales
    ADD CONSTRAINT estados_obras_sociales_pkey PRIMARY KEY ("ID_EstadoObraSocial");


--
-- Name: estados_pacientes estados_pacientes_estado_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes
    ADD CONSTRAINT estados_pacientes_estado_key UNIQUE ("Estado");


--
-- Name: estados_pacientes estados_pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_pacientes
    ADD CONSTRAINT estados_pacientes_pkey PRIMARY KEY ("ID_EstadoPaciente");


--
-- Name: estados_profesionales estados_profesionales_estado_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_profesionales
    ADD CONSTRAINT estados_profesionales_estado_key UNIQUE ("Estado");


--
-- Name: estados_profesionales estados_profesionales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_profesionales
    ADD CONSTRAINT estados_profesionales_pkey PRIMARY KEY ("ID_EstadoProfesional");


--
-- Name: estados_turnos estados_turnos_estado_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos
    ADD CONSTRAINT estados_turnos_estado_key UNIQUE ("Estado");


--
-- Name: estados_turnos estados_turnos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estados_turnos
    ADD CONSTRAINT estados_turnos_pkey PRIMARY KEY ("ID_EstadoTurno");


--
-- Name: obras_sociales obras_sociales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales
    ADD CONSTRAINT obras_sociales_pkey PRIMARY KEY ("ID_ObraSocial");


--
-- Name: pacientes pacientes_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_dni_key UNIQUE ("DNI");


--
-- Name: pacientes pacientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT pacientes_pkey PRIMARY KEY ("ID_Paciente");


--
-- Name: pacientes_tutores pacientes_tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT pacientes_tutores_pkey PRIMARY KEY ("ID_PacienteTutor");


--
-- Name: parentescos parentescos_descripcion_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos
    ADD CONSTRAINT parentescos_descripcion_key UNIQUE ("Descripcion");


--
-- Name: parentescos parentescos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parentescos
    ADD CONSTRAINT parentescos_pkey PRIMARY KEY ("ID_Parentesco");


--
-- Name: permisos permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_pkey PRIMARY KEY ("ID_Permiso");


--
-- Name: profesionales profesionales_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_dni_key UNIQUE ("DNI");


--
-- Name: profesionales profesionales_matricula_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_matricula_key UNIQUE ("Matricula");


--
-- Name: profesionales profesionales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT profesionales_pkey PRIMARY KEY ("ID_Profesionales");


--
-- Name: registros_de_sesiones registros_de_sesiones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_de_sesiones
    ADD CONSTRAINT registros_de_sesiones_pkey PRIMARY KEY ("ID_RegistroSesion");


--
-- Name: roles_permisos roles_permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT roles_permisos_pkey PRIMARY KEY ("ID_RolPermiso");


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY ("ID_Rol");


--
-- Name: roles roles_rol_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_rol_key UNIQUE ("Rol");


--
-- Name: tipos_obras_sociales tipos_obras_sociales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales
    ADD CONSTRAINT tipos_obras_sociales_pkey PRIMARY KEY ("ID_TipoOS");


--
-- Name: tipos_obras_sociales tipos_obras_sociales_tipo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_obras_sociales
    ADD CONSTRAINT tipos_obras_sociales_tipo_key UNIQUE ("Tipo");


--
-- Name: turnos turnos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT turnos_pkey PRIMARY KEY ("ID_Turnos");


--
-- Name: tutores tutores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tutores
    ADD CONSTRAINT tutores_pkey PRIMARY KEY ("ID_Tutor");


--
-- Name: pacientes_tutores uq_paciente_tutor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT uq_paciente_tutor UNIQUE ("ID_Paciente", "ID_Tutor");


--
-- Name: usuarios uq_usuarios_usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uq_usuarios_usuario UNIQUE ("Usuario");


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY ("ID_Usuario");


--
-- Name: uq_paciente_responsable_principal; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_paciente_responsable_principal ON public.pacientes_tutores USING btree ("ID_Paciente") WHERE ("ResponsablePrincipal" = true);


--
-- Name: uq_turno_profesional_fecha_hora; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_turno_profesional_fecha_hora ON public.turnos USING btree ("ID_Profesional", "Fecha", "Hora");


--
-- Name: uq_turno_registro_sesion; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_turno_registro_sesion ON public.turnos USING btree ("ID_RegistroSesion") WHERE ("ID_RegistroSesion" IS NOT NULL);


--
-- Name: asignaciones_profesionales fk_asignacionesprofesionales_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT fk_asignacionesprofesionales_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente");


--
-- Name: asignaciones_profesionales fk_asignacionesprofesionales_profesional; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asignaciones_profesionales
    ADD CONSTRAINT fk_asignacionesprofesionales_profesional FOREIGN KEY ("ID_Profesional") REFERENCES public.profesionales("ID_Profesionales");


--
-- Name: obras_sociales fk_obrassociales_estados; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales
    ADD CONSTRAINT fk_obrassociales_estados FOREIGN KEY ("ID_EstadoObraSocial") REFERENCES public.estados_obras_sociales("ID_EstadoObraSocial");


--
-- Name: obras_sociales fk_obrassociales_tipos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obras_sociales
    ADD CONSTRAINT fk_obrassociales_tipos FOREIGN KEY ("ID_TipoOS") REFERENCES public.tipos_obras_sociales("ID_TipoOS");


--
-- Name: pacientes fk_pacientes_estados; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT fk_pacientes_estados FOREIGN KEY ("ID_EstadoPaciente") REFERENCES public.estados_pacientes("ID_EstadoPaciente");


--
-- Name: pacientes fk_pacientes_obrassociales; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes
    ADD CONSTRAINT fk_pacientes_obrassociales FOREIGN KEY ("ID_ObraSocial") REFERENCES public.obras_sociales("ID_ObraSocial");


--
-- Name: pacientes_tutores fk_pacientestutores_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente") ON DELETE CASCADE;


--
-- Name: pacientes_tutores fk_pacientestutores_parentesco; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_parentesco FOREIGN KEY ("ID_Parentesco") REFERENCES public.parentescos("ID_Parentesco");


--
-- Name: pacientes_tutores fk_pacientestutores_tutor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pacientes_tutores
    ADD CONSTRAINT fk_pacientestutores_tutor FOREIGN KEY ("ID_Tutor") REFERENCES public.tutores("ID_Tutor") ON DELETE CASCADE;


--
-- Name: profesionales fk_profesionales_especialidades; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_especialidades FOREIGN KEY ("ID_Especialidad") REFERENCES public.especialidades("ID_Especialidad");


--
-- Name: profesionales fk_profesionales_estadoprofesional; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_estadoprofesional FOREIGN KEY ("ID_EstadoProfesional") REFERENCES public.estados_profesionales("ID_EstadoProfesional");


--
-- Name: profesionales fk_profesionales_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_rol FOREIGN KEY ("ID_Rol") REFERENCES public.roles("ID_Rol");


--
-- Name: profesionales fk_profesionales_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profesionales
    ADD CONSTRAINT fk_profesionales_usuario FOREIGN KEY ("ID_Usuario") REFERENCES public.usuarios("ID_Usuario");


--
-- Name: roles_permisos fk_rolespermisos_permiso; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT fk_rolespermisos_permiso FOREIGN KEY ("ID_Permiso") REFERENCES public.permisos("ID_Permiso");


--
-- Name: roles_permisos fk_rolespermisos_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles_permisos
    ADD CONSTRAINT fk_rolespermisos_rol FOREIGN KEY ("ID_Rol") REFERENCES public.roles("ID_Rol");


--
-- Name: turnos fk_turnos_estados; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_estados FOREIGN KEY ("ID_EstadoTurno") REFERENCES public.estados_turnos("ID_EstadoTurno");


--
-- Name: turnos fk_turnos_paciente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_paciente FOREIGN KEY ("ID_Paciente") REFERENCES public.pacientes("ID_Paciente");


--
-- Name: turnos fk_turnos_profesional; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_profesional FOREIGN KEY ("ID_Profesional") REFERENCES public.profesionales("ID_Profesionales");


--
-- Name: turnos fk_turnos_registrosesion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.turnos
    ADD CONSTRAINT fk_turnos_registrosesion FOREIGN KEY ("ID_RegistroSesion") REFERENCES public.registros_de_sesiones("ID_RegistroSesion") ON DELETE SET NULL;


--
-- Name: usuarios fk_usuarios_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_rol FOREIGN KEY ("ID_Rol") REFERENCES public.roles("ID_Rol");


--
-- PostgreSQL database dump complete
--

\unrestrict wCyt4KEMGHEjKsrzC5ODss8b249UFkShbL4PsaU0u3YzrUE9uTCP3xgXEJ7gFrz

